### PR TITLE
Update README links

### PR DESCRIPTION
**Pull request by JeromeDeLeon**

### CODE REVIEW

**Comment by JeromeDeLeon** [comment]
Really, hard to keep tracks of different README 😆

**Comment by JeromeDeLeon** [comment]
plus, prettier problem 🤣

**Comment by bluebill1049** [comment]
lol @JeromeDeLeon thanks buddy :)

**Comment by JeromeDeLeon** [comment]
Why CI fails?

**Comment by bluebill1049** [comment]
God knows lol 

```internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/367/lib/node_modules/wait-on/node_modules/core-js/postinstall'```

this happens sometimes.

**Comment by JeromeDeLeon** [comment]
Does this happen because of constantly committing without finishing the previous one?

**Comment by bluebill1049** [comment]
probably yes :) smart!

**Comment by JeromeDeLeon** [comment]
Let's see for the next one. I was searching this issue and seemed like CI failed to install all the modules.

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@types/react/-/react-16.8.23.tgz: ETIMEDOUT".
```

That's why it cannot find the module `postinstall`.
Many suggest changing the registry:
`npm config set registry http://registry.npmjs.org/`
or set proxy to `null`:
`npm config set proxy null`

I'd like to observe more because I don't want to break things up.

**Comment by bluebill1049** [comment]
nah it's all good, you didn't break anything. let's keep an eye on it next time. 👍

**Pull request merged**
