### PR TITLE
Add named component export

### LINKED ISSUE #10465: issue: Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
### Version Number

7.44.2

### Codesandbox/Expo snack

-

### Steps to reproduce

When I want to build my app on CRA. I got an error
`
Creating an optimized production build...
Failed to compile.
./node_modules/react-hook-form/dist/index.esm.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
`

### Expected behaviour

Build

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Moshyfawn**
Closes: #10465

### CODE REVIEW

**Comment by bluebill1049** [comment]
oh really???

**Comment by bluebill1049** [comment]
image

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
> This PR fixes the export issue, @bluebill1049. You can try it in [this codesandbox `success` branch](https://codesandbox.io/p/github/Moshyfawn/rhf-deps-test/rc?file=%2Fsrc%2FApp.js%3A10%2C41&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clicbernx000b3b6k6nvirf3u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clicbernx000d3b6kuplfrvu5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clicbernx000b3b6k6nvirf3u%2522%253A%257B%2522id%2522%253A%2522clicbernx000b3b6k6nvirf3u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clicbicxz016c3b6khj3jkw8m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clidpmppf00863b6lawbg9g6c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clidpmppf00863b6lawbg9g6c%2522%257D%252C%2522clicbernx000d3b6kuplfrvu5%2522%253A%257B%2522id%2522%253A%2522clicbernx000d3b6kuplfrvu5%2522%252C%2522activeTabId%2522%253A%2522clidq3xbh023x3b6lreinnn09%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clicbfmyj00fe3b6kr2kfd6v7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clicbj31f01rl3b6kxqwa0cjp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522clicbj99v01u53b6ktm1m4mgp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clicbjd6e000vfxcw3ylkfkbj%2522%257D%252C%257B%2522id%2522%253A%2522clidq3xbh023x3b6lreinnn09%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Project not found, but I trust you!

**Comment by Moshyfawn** [comment]
I can't say I'm 💯 sure 

> > This PR fixes the export issue, @bluebill1049. You can try it in [this codesandbox `success` branch](https://codesandbox.io/p/github/Moshyfawn/rhf-deps-test/rc?file=%2Fsrc%2FApp.js%3A10%2C41&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clicbernx000b3b6k6nvirf3u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clicbernx000d3b6kuplfrvu5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clicbernx000b3b6k6nvirf3u%2522%253A%257B%2522id%2522%253A%2522clicbernx000b3b6k6nvirf3u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clicbicxz016c3b6khj3jkw8m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clidpmppf00863b6lawbg9g6c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clidpmppf00863b6lawbg9g6c%2522%257D%252C%2522clicbernx000d3b6kuplfrvu5%2522%253A%257B%2522id%2522%253A%2522clicbernx000d3b6kuplfrvu5%2522%252C%2522activeTabId%2522%253A%2522clidq3xbh023x3b6lreinnn09%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clicbfmyj00fe3b6kr2kfd6v7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clicbj31f01rl3b6kxqwa0cjp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522clicbj99v01u53b6ktm1m4mgp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clicbjd6e000vfxcw3ylkfkbj%2522%257D%252C%257B%2522id%2522%253A%2522clidq3xbh023x3b6lreinnn09%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
> 
> Project not found, but I trust you!

Ooof, not sure why, but should work now _(directly copied the link instead of using their "share" feature)_

**Comment by bluebill1049** [comment]
Going to publish it now since it impacts so many users. 🚀

**Comment by Moshyfawn** [comment]
> Going to publish it now since it impacts so many users. 🚀

🔥 sounds good!

**Pull request merged**
