### PR TITLE
Refactor useFieldArray test

### PR DESCRIPTION
**Pull request by keiya01**
- I wrapped test for each method in `useFieldArray` by `describe` method
- I removed duplicated test in `useFieldArray`
- I fixed `appendId` method test in `mapIds.test.ts`

### CODE REVIEW

**Comment by bluebill1049** [comment]
awesome! thanks for the test refinement. 💖

**Comment by bluebill1049** [comment]
@keiya01 you should start a branch from master now :) you are a member now. you don't need fork anymore.

**Comment by keiya01** [comment]
@bluebill1049 
Oops... I unintentionally did my usual routine.
OK! I will start a branch from master at next PR.

**Comment by bluebill1049** [comment]
lol all good, in case you forgot lol

**Pull request merged**
