### PR TITLE
Feature/support ie11

### PR DESCRIPTION
**Pull request by michaelbirchler**
With the following `compilerOptions` adjustments and the required polyfills everything is working fine with IE11. We didn't found any incompatibilities yet.

* Adjust the compilerOptios to add support for IE11, more details here: #56
* `"downlevelIteration": true` is needed so object spreading is transpiled correctly for ES5 (https://mariusschulz.com/blog/downlevel-iteration-for-es3-es5-in-typescript).

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks, @michaelbirchler I will give it a try, see how much bigger the bundler is producing. if it's getting too big, I may just release separate IE only version without impact the size of the package.

**Comment by bluebill1049** [comment]
Do you want to try this version? I have built with your config
react-hook-form@3.18.10-ie.11

**Comment by bluebill1049** [comment]
Screen Shot 2019-07-23 at 4 21 56 pm

thanks for contributing 👍

**Comment by michaelbirchler** [comment]
> Do you want to try this version? I have built with your config
> react-hook-form@3.18.10-ie.11
> 
> If this works I can include that in the documentation.

@bluebill1049 thank you 🙇 , if tested the version _react-hook-form@3.18.10-ie.11_ and it just works fine 👍

**Comment by bluebill1049** [comment]
Cool! I will update the website documentation and release IE version with tag 🏷. Thank you for ur contribution again

**Comment by holloway** [comment]
@bluebill1049 thanks for supporting this old browser!

It seems that the latest release `3.21.1-ie11` has an iterable error again, but the `3.18.10-ie.11` release works. The `3.21.1-ie11` release is labelled 'beta' though so perhaps it hasn't been tested yet.

Thanks again.. this works great for me :)

**Comment by bluebill1049** [comment]
@holloway my bad, I have published the wrong IE version: `3.21.4-ie11`

**Pull request merged**
