### PR TITLE
improve FieldPath type to support tuple type

### PR DESCRIPTION
**Pull request by kotarella1110**
## 1. support tuple type

```tsx
type FormValues = {
  tuple: [{
    name: string;
    contributors: number;
  }, {
    name: string;
    contributors: number;
  }];
};

<input {...register("tuple.0.name")} />
<input {...register("tuple.1.contributors")} />
<input {...register("tuple.2.name")} /> // type error
```

### Before

スクリーンショット 2021-03-01 18 54 30

### After

スクリーンショット 2021-03-01 18 54 53

## Ref

- [CodeSandbox](https://codesandbox.io/s/react-hook-form-4317-qjwbw?file=/src/App.tsx)
- [TypeScript Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAKUCWBbTNMBuqAvAFBxwA+cAdgK4A2D5VcdNAJsAGaY3AcW1AM4wsNAOZDadbACNgUaXIgQGwAIY1pwxPLXLMEvjADcpJCjgBJYQBU6YdQB47cUDGCdhcLYgDaALoAfHDEMvKK7iCe3nB2-gBE6pIwABaJgXAA-HDcGgzCqABcCFB0wOaWqACCUFAaiADSwIhhEQpQVcioDk7ALYiu0bEcPn5BoeEAoiAAxgx0XM4A1q0Q3PEANHBriBu+NAEhFj02whg4eITArlPxI15j6Fi4+EQ5ZRVwpfmFlaRTlY0Bp0nd2m4PE8fAAlTQcCA0BiIOoNIZ8bhRABqwRYuVslzeN2cOMecTEFRYFHx9kcLjcADJDsdQlDyeVgFSKJ8AAYAEgA3n11INhkyJiE4EzROIJABfHlciilfkC1GNQYKrmlWzC26M5mTMnPCmc7k5JXc6iqvWig0S0LSsR8eWK83m62C22tMWGyVO2VygB0gpBYJxWvNKsF6uarQVrFVsc1IYFYbSJOCkZ+cAFlv8TTgfF2602dkCOour2uRFcBclbJNHMt1LghYDLpbOYAFO24DKXQBKROCvsDyTB0OgjMJJohBXmc1y-x7A7l8ykUCQWAIM7prEFCrOFh2LYsNDGnzpu6ke4Xxs+VUYqJNScC59QOAw7O5QsPkv7GWXK5DCl7oNOdZzri7qfPuh76vWOwwtB7qlPwRBKFGbZSnAyatGBq5AeauRwYsCF9nhiCBEhOHXrOOGUSEKHKrQwAYSwpT3jE0IAWueLxP4aCBBx6AMfUGr4f+hHxPxCQXkyjEiehigblwCwaFAqDcOwcz4IicASMAMCuDsXGjFeEF2MEwTdhAcgAFalKecBgNOnGDpx04HmRJnoMEG7VHAADyDntHmFAyqU44SIuERobInSxTAdLAAAjKU-jRTs9CRFAgRJSlABMGXhdyNAaNgwBRc6kixRQcyIs6ch0DA0DCPFuWxXKOylRQ5WVdVsp1XADU0E1LVtR1iUsHK+UsBpaLpf2NUSEEsULY0xW5ly-VVctQ1cqN42tVA7UdCpM1rSwdn2cAumlL1tAVXt0XDUdWDNSdZ05dNFByuY-2AqNohwDdd0wKUIX2WFcq+OMRwbuo8A5e0qUboZMC2Q54M7IkNAQDAsyYKIwiJIO5gY1jt26bjyX9KlQYAAxkxTRlUzjcCJHT6gM6lLOkJTYM05z3NpUGhX84L2PC1zRVM5LbNCzAtNywz72YJ9bUK5jSsq-0hXi9r7MyxtiC84zjMS+TAuK9LytwDypsM4KOUJhoPjAzA1tS9T9uJKbBuM0G6ua6dRu65zAdBgArAAbMHjUfRNYfe7bvu41HqUWwALEGu3h3bOyO+JiAGy7sjBiHyfCDycMjYioipzrhec0rCdjUnX380AA)

### CODE REVIEW

**Comment by bluebill1049** [comment]
looks like build failed.

**Comment by kotarella1110** [comment]
@bluebill1049 I was able to avoid the build error by exporting `Path` and `PathValue` type 👍
strange... 😅

https://github.com/react-hook-form/react-hook-form/pull/4317/commits/15408d93081015ca9ec624fdf541bb9190980ec3

**Comment by bluebill1049** [comment]
> @bluebill1049 I was able to avoid the build error by exporting `Path` and `PathValue` type 👍
> strange... 😅
> 
> [15408d9](https://github.com/react-hook-form/react-hook-form/commit/15408d93081015ca9ec624fdf541bb9190980ec3)

wow that's so strange.

**Comment by bluebill1049** [comment]
Thank you very much @kotarella1110 for the type improvement.

**Pull request merged**
