### PR TITLE
config for auto un-register

### LINKED ISSUE #1713: V6: Message type requires a cast to string when used on a string only field.
**Describe the bug**
This is more of an annoyance with the typing. This requires all props that you feed `errors.fieldName?.message` into to support both `string` and `ReactElement` or always require a cast to the correct typing.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-s2687?file=/src/index.tsx

**Expected behavior**
Not to have to cast every usage of an error message

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

### PR DESCRIPTION
**Pull request by bluebill1049**
**V6 feature:**

This feature will solve an issue when users want to persis their inputs without `unregister` invoked by `mutationObserver`. 

```tsx
useform({
  shouldUnregister: false
})
```

above config will disable `unregister` when inputs get unmounted and give user the option to keep value inside the hook store.

https://codesandbox.io/s/autounregister-4e91k?file=/src/src/logic/findRemovedFieldAndRemoveListener.ts

fix #1713 for the error message to be strictly typed for `string`.

### CODE REVIEW

**Review by JeromeDeLeon — DISMISSED** [review]
LGTM! Seems pretty useful feature for conditional fields.

**Comment by JeromeDeLeon** [comment]
[#186](https://github.com/react-hook-form/react-hook-form/issues/186) [#1709](https://github.com/react-hook-form/react-hook-form/issues/1709) These issues could be resolved by this feature, I suppose?

**Comment by JeromeDeLeon** [comment]
This looks great really! I think it could improved our case for conditional rendering especially when it has the ability to set value even when field is not render on screen. Greate Job!

**Comment by bluebill1049** [comment]
Thanks @JeromeDeLeon yes, I think a lot of users still live in the Controlled input land, so this will let them breathe, while we still embrace native form validation behavior.

**Pull request merged**
