### PR TITLE
create own file for env detect

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by bluebill1049** [comment]
@JeromeDeLeon going to keep those variable inline 😱

**Comment by JeromeDeLeon** [comment]
Why? Though its fine for me. Just curious.

**Comment by bluebill1049** [comment]
+326 B 😭

**Comment by JeromeDeLeon** [comment]
Oh god why? Why is it that when you move it to a seprate file makes a big difference than just spreading it inside?
 :disappointed:

**Comment by JeromeDeLeon** [comment]
Maybe they were creating import statement and such that's why its adding few lines of code hence the result of such size. Okay, we couldn't do about it. Yeah, great better not move it if its the case.

**Comment by bluebill1049** [comment]
> Maybe they were creating import statement and such that's why its adding few lines of code hence the result of such size. Okay, we couldn't do about it. Yeah, great better not move it if its the case.

yea, worth testing it out anyhow :( it's ugly because save us some bytes.

**Pull request closed without merging**
