### PR TITLE
skip early on validate function

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by JeromeDeLeon** [comment]
It would now be inconsistent IMO if this would not be the same as `abortEarly` using `Yup` schema.
I'm not saying this is bad, but if this approach is going to be push, might as well update `abortEarly` to support the same behavior for consistency. :smile

**Comment by JeromeDeLeon** [comment]
Similar to my question before, about the difference between `abortEarly` because I thought that would also stop from validating the rest if one emits an error.

**Comment by bluebill1049** [comment]
Yea true! Maybe we should one option for both?

**Comment by JeromeDeLeon** [comment]
We would break the current API if we flatten the option for `abortEarly` but would allow us to be consistent.

**Comment by bluebill1049** [comment]
Maybe we should skip early to true by default?

**Comment by JeromeDeLeon** [comment]
Better if we set it to `false`for backward compatibility.

**Comment by bluebill1049** [comment]
This is one of the mistake that i have made.... for validation (required, max, min) they actually skip early, but then valdiation schema is abortEarly false...

**Comment by bluebill1049** [comment]
I am thinking of correcting them all in one go by set abortEarly to true for all...

**Comment by bluebill1049** [comment]
or I can just fix in this PR and leave schema validation as it is right now

**Comment by JeromeDeLeon** [comment]
I see, then apply this PR first then we can have discussion with other members later

**Comment by bluebill1049** [comment]
personally I am towards fix validation to be consistent and ignore validation schema for now.
 your thoughts?

**Comment by bluebill1049** [comment]
ok @JeromeDeLeon thanks

**Comment by JeromeDeLeon** [comment]
I opened a discussion for this or should I opened it publicly to know opinion of others?

**Comment by bluebill1049** [comment]
sounds good @JeromeDeLeon

**Review by JeromeDeLeon — APPROVED** [review]
LGTM! 👍

**Pull request merged**
