### PR TITLE
💚 ci: Generate package builds on PR

### PR DESCRIPTION
**Pull request by Moshyfawn**
# Features
- Generate a sharable package build on successful PR request.

image

- Create a codesanbox from [RHF V7 TS template](https://codesandbox.io/s/rhf-v7-ts-template-x9gjdy?file=%2Fsrc%2FApp.tsx) with the package build dependency with PR changes
```json
"dependencies": {
  "react": "^18",
  "react-dom": "^18",
  "react-scripts": "latest",
  "react-hook-form": "https://pkg.csb.dev/Moshyfawn/react-hook-form/commit/ec727709/react-hook-form"
}
```
# Info
If we go through with this PR, @bluebill1049 will need to authorize [the CodeSandbox CI GitHub app](https://github.com/apps/codesandbox) with react-hook-form/react-hook-form

### CODE REVIEW

**Comment by bluebill1049** [comment]
It's already authorized :)

**Comment by bluebill1049** [comment]
U want to use those: https://codesandbox.io/dashboard/templates?workspace=ff6b43a6-e1ee-44da-89f1-3c242706d305 

it has a TS and JS template.

**Comment by Moshyfawn** [comment]
> U want to use those: https://codesandbox.io/dashboard/templates?workspace=ff6b43a6-e1ee-44da-89f1-3c242706d305
> 
> it has a TS and JS template.

Ah, makes sense! I was fiddling with the build and React 18.
Would you consider upgrading [these](https://codesandbox.io/dashboard/templates?workspace=ff6b43a6-e1ee-44da-89f1-3c242706d305) some time in the future?

**Comment by bluebill1049** [comment]
feel free to upgrade them to react 18 :) it should just worked as well.

**Comment by Moshyfawn** [comment]
> feel free to upgrade them to react 18 :) it should just worked as well.

Got upgraded!

**Comment by bluebill1049** [comment]
thank you!

**Review by bluebill1049 — APPROVED** [review]

**Comment by Moshyfawn** [comment]
Wanna try a build or wait until the next PR? Can't think of a small change :P

**Comment by bluebill1049** [comment]
let's wait for the next pr, it's going to work 👍 it was working before as well. (i took it off because the usage was low, we can leverage again now)

**Comment by Moshyfawn** [comment]
> let's wait for the next pr, it's going to work 👍 it was working before as well. (i took it off because the usage was low, we can leverage again now)

Sounds good!

It's just super convenient to be able to use the new build changes and test out things in a CSB!

I had an issue with [Jotai](https://github.com/pmndrs/jotai) the other day and I was able to test the fix before it got deployed! :P

**Pull request merged**
