### PR TITLE
fix #2191 with unset nested error

### LINKED ISSUE #2191: Submit handler won't fire even after validations pass
**Describe the bug**
In a form with a `validate` prop set on `register`, the submit handler won't fire after the user fixes a validation error.

**To Reproduce**
1. Go to https://codesandbox.io/s/smoosh-sunset-t8q22?file=/src/App.js
2. Enter some numeric value for the Count 1 field, and then some numeric value for the Weight 1 field, and see the form getting submitted (this is expected).
3. Now refresh the page, and on refresh, press submit without entering anything. Notice validation failures in the console (this is expected).
4. Now without refreshing, enter some numeric value for Count 1, and some numeric value for Count 2, and click on Submit.
5. Notice that validation succeeds (see console, and this is expected) **but** the form's submit handler won't fire. This is the problem, as I'd expect the form to submit now that all validations pass.

**Codesandbox link**
https://codesandbox.io/s/smoosh-sunset-t8q22?file=/src/App.js

**Expected behavior**
On submitting the form after all validation errors are fixed, the submit handler should be fired.

**Desktop:**
 - OS: macOS Mojave 10.14.6
 - Browser Chrome 85.0.4183.16 (Official Build) dev (64-bit)
 - Version `react-hook-form` v6.0.4

**Additional context**
Might be somewhat related to https://github.com/react-hook-form/react-hook-form/issues/2180, but I'm not a 100% sure.

**Quick note about the validation logic**

1. `atLeast1Count` - The user is expected to enter input for at least one of the 'Count' fields.
2. `requiredWeight` - For every 'Count' field that has a value > 0, the corresponding 'Weight' field should also have a value.

### PR DESCRIPTION
**Pull request by bluebill1049**
- [x] unit tests

close #2191

### CODE REVIEW

**Review by JeromeDeLeon — DISMISSED** [review]
LGTM! :heart:

**Comment by bluebill1049** [comment]
> LGTM! ❤️

Thank you for your review :)

**Comment by paambaati** [comment]
@bluebill1049 Thank you so much for fixing this quickly. Is there an ETA for a release that includes this fix?

**Comment by keiya01** [comment]
LGTM :)

**Pull request merged**
