### PR TITLE
Refactor useForm

### PR DESCRIPTION
**Pull request by keiya01**
**Did**

I refactored code in useForm. I added some Hooks to bundle meaningful functions.

**Why**

Because when I read react-hook-form code, I feel it is difficult to find applicable code. 
And if react-hook-form is modified or added some features, I think it makes be difficult to find code each time.
Additionally, I think  it makes be difficult to write test, when a function has many features.

But splitting file is increased bundle size...

I consider I want to refactor other code in useForm, if this proposal is approved.

Thank you for reading a proposal. And I'm sorry modified code is too many...

### CODE REVIEW

**Comment by bluebill1049** [comment]
hey @keiya01 thanks a lot for the refactoring, let's have a chat next time before refactoring `useForm`. I don't think we will go forward this PR due to the package size increase, in fact, I do care a lot about the package size, and hence not breaking the main useForm into too many files.

**Comment by keiya01** [comment]
I see. Thank you for reading PR.

**Comment by bluebill1049** [comment]
Thanks for understanding @keiya01 and I am sorry to not accepting your hard work. 😢

**Comment by bluebill1049** [comment]
but please feel free to move around and change things to make it more sense, the best is not crease the package size. the smaller the better.

**Comment by keiya01** [comment]
No problem. I should have confirmed before send PR...

**Comment by bluebill1049** [comment]
I just realize you are the no.4 contributor for this lib... and you are not even the team member.
Screen Shot 2020-06-14 at 9 57 59 pm

**Comment by keiya01** [comment]
Wow... I'm glad if my contributions are helpful for you.

**Comment by bluebill1049** [comment]
> Wow... I'm glad if my contributions are helpful for you.

you are helping thousands of developers around the world. ❤️

**Comment by keiya01** [comment]
I think RHF should be used by more developers. RHF is very helpful.

**Pull request closed without merging**
