### PR TITLE
close #1090 controller get value

### LINKED ISSUE #1090: Add a way to skip Contorller#commonTask getInputValue() call
**Is your feature request related to a problem? Please describe.**

When use Controller with custom input, If the value object is {id:1, value:"ABC"}, controller will set next value to "ABC" because getInputValue will try to get obj.value first. Should it be {id:1, value:"ABC"}? 

https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.tsx#L59
and 
https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getInputValue.ts#L13

**Describe the solution you'd like**

Maybe we should only call `getInputValue` if `value` is an `SyntheticEvent` object? Can we rely on constructor check?
```tsx
if (e.constructor.name === "SyntheticEvent" && e.type === "change") {
  console.log("input change event");
}
```

**Describe alternatives you've considered**

Or can we add an option to skip it?

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by bluebill1049** [comment]
beta:

yarn add https://pkg.csb.dev/react-hook-form/react-hook-form/commit/b4f974b7/react-hook-form

**Comment by xiaoyu-tamu** [comment]
I'm just wondering what if user provide object `{ target: { id: 1, value: 'a' } }` as value? Looks like I still get 'a'. 

This happened when people use Mateiral-UI Autocomplete component or component that store whole object internal. e.g. 
```
<Autocomplete    
      options={[{ target: { id: 1, value: 'a' } }]}
      getOptionLabel={o => o?.target?.value} />

```

**Comment by bluebill1049** [comment]
aha i see, will make the adjustment. My goal is to keep simple and try to write as less code as possible.

**Comment by xiaoyu-tamu** [comment]
Definitely

**Comment by bluebill1049** [comment]
let's check `e.type` as well, can't do `instanceof Event` due to react-native.

**Comment by xiaoyu-tamu** [comment]
> let's check `e.type` as well, can't do `instanceof Event` due to react-native.

Sound good, we may need to update doc for controller to let developer know that when the value is following shape, they may get unexpected result. 
```
{
    target: {
         type:any,
         value: any,
   }
}
```

**Comment by bluebill1049** [comment]
Yeah totally!

**Pull request merged**
