### PR TITLE
fix: resolve type of set function

### PR DESCRIPTION
**Pull request by vismay7**
I have made changes to get the suggestion on set object path. It will make developer live easy with such cool suggestion. 
Feel free to comment as it's my first PR in such great community repo :smile:.

### CODE REVIEW

**Comment by vismayZN** [comment]
@bluebill1049 Can you please take a look?

**Comment by vismay7** [comment]
@bluebill1049, Can you please look at this?

**Review by vatsalagola — APPROVED** [review]

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
LGTM! thanks

**Review by gustavoabel — APPROVED** [review]

**Comment by vismay7** [comment]
@bluebill1049 I would like to follow up on the pull request I submitted. It has been approved, but I believe it is still awaiting merge.

**Pull request merged**
