### PR TITLE
feat: added smart form component

### PR DESCRIPTION
**Pull request by alirezakarimidev**
This component appears to be a wrapper around the useForm hook.
This wrapper aims to simplify the usage of the form handling logic and provide a more structured and reusable way to manage forms in our application.
We can easily use this component without using useForm hook directly.

Well documented
Added type declaration for it
Added some basic tests

### CODE REVIEW

**Comment by hoomantalakian** [comment]
That's an interesting feature. I think it would be useful to incorporate this feature into this Library!

**Comment by Moshyfawn** [comment]
Thank you for your time and the contribution, Alireza!

Unfortunately, I don't think we want to expand the RHF API with a component wrapper around the `useForm` hook as it can easily be done in user-land.

Unless @bluebill1049 thinks otherwise.

**Comment by Moshyfawn** [comment]
Additionally, there's a new [`Form` component](https://react-hook-form.com/docs/useform/form) that encompasses additional request API logic on top of the standard `useForm` API in RHF

**Comment by GetWrecked99** [comment]
Thank you for your response @Moshyfawn

Honestly, it doesn't significantly alter the manner in which you employ it. It hinges upon the developer's preferred approach for implementing the form's logic.
One of the reasons I developed this was its applicability to server components, particularly the recently introduced Next.js app directory feature. You need not concern yourself with utilizing the useForm hook in server components any longer.


form-props

Form-Methods

**Comment by bluebill1049** [comment]
Thanks for the awesome contribution @GetWrecked99! Apologies for the late reply. Would you be keen to publish that as your own package? we can include that in the FAQ as an external package to be used by users.

**Comment by GetWrecked99** [comment]
Thank you for your response @bluebill1049 and I appreciate your feedback on my contribution. While I'm glad to hear that you found the contribution valuable, I would like to continue improving the feature before considering it as a standalone package.

I plan to work on adding more features and refining the codebase to make it even more robust and user-friendly. Once I feel it's in a more polished state, I'll certainly consider publishing it as its own package.

I'll keep you updated on the progress.

Best Regards,
Alireza

**Pull request closed without merging**
