### PR TITLE
Fix a rollup config for ie11

### PR DESCRIPTION
**Pull request by yhor1e**
For #2488. 

Please check this PR. Thanks.

### CODE REVIEW

**Review by kotarella1110 — APPROVED** [review]
Awesome PR 💯 
Thanks 👍

**Comment by bluebill1049** [comment]
thanks @kotarella1110 for the review.

**Comment by yhor1e** [comment]
Thank you, @bluebill1049 and @kotarella1110.

**Comment by bluebill1049** [comment]
Thank you @yhor1e 🙏

**Pull request merged**
