### PR TITLE
fix: correct type of `error` field in `getFieldState` return object

### LINKED ISSUE #11814: issue: `getFieldState(..).error` type is incorrect
### Version Number

7.51.3

### Codesandbox/Expo snack

[Codesandbox link here](https://codesandbox.io/p/sandbox/rhf-zod-resolver-issue-3w722c?file=%2Fsrc%2FForm.tsx%3A65%2C34&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvcsor2t00063b6gtxqzb8ll%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvcsor2t00023b6g4l0u4ode%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvcsor2t00033b6g6q3vjolx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvcsor2t00053b6gbz1rv5em%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B45.87609459787216%252C54.12390540212784%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvcsor2t00023b6g4l0u4ode%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvcsor2t00013b6gfwnzlm3y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvcsw9gf00023b6gzmiabdpk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A65%252C%2522startColumn%2522%253A34%252C%2522endLineNumber%2522%253A65%252C%2522endColumn%2522%253A34%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FForm.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvcsor2t00023b6g4l0u4ode%2522%252C%2522activeTabId%2522%253A%2522clvcsw9gf00023b6gzmiabdpk%2522%257D%252C%2522clvcsor2t00053b6gbz1rv5em%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvcsor2t00043b6gnm1r8yyw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvcsor2t00053b6gbz1rv5em%2522%252C%2522activeTabId%2522%253A%2522clvcsor2t00043b6gnm1r8yyw%2522%257D%252C%2522clvcsor2t00033b6g6q3vjolx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvcsor2t00033b6g6q3vjolx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

I'm using the Zodresolver ("@hookform/resolvers": "^3.3.4") to do the validation. That might be related.

I've pasted the instructions from the Codesandbox page below. I added a regular string field ("nickname") to the demo as a control to demonstrate that non-array fields work correctly.

Instructions:
1. Notice how there are no errors starting out

2. Click "Submit"

3. Notice how `form.getFieldState("files").error?.message` is filled. That is because the error is on the array level of the schema (`z.arr(..).min(1)`)

4. Click "Choose files" and add a file

5. Notice how `form.getFieldState("files").error?.message` is no longer filled. It's undefined (see console)

6. But notice now that `form.getFieldState("files").error?.[0]?.message` IS filled. Same goes for `form.formState.errors.files?.[0]?.message`

7. So `getFieldState(..).error` should share the signature of `formState.errors.x`, namely `Merge<FieldError, (FieldError | undefined)[]> | undefined`. However, it is typed only as `FieldError | undefined`

8. Check the code and look for the type error and my comment. You can verify the incorrect types there

### Expected behaviour

I expect the type of `getFieldState(..).error` to be `Merge<FieldError, (FieldError | undefined)[]> | undefined`, instead of `FieldError | undefined`. `formState.errors.<field>`'s type is in fact `Merge<FieldError, (FieldError | undefined)[]> | undefined`, which I think is the correct type for both. That is because a field's error can be an array of `FieldError`s or it could be a single `FieldError`, as shown in the demo (`files` and `nickname` fields, respectively).

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cj-young**
To fix #11814.

I changed the type of the `error` field inside the return object of a form's `getFieldState` to be more general. The current implementation doesn't account for nested errors inside objects since it uses the basic `FieldError` type. I changed it to an indexed access type that uses the type of the actual errors object present in the form state, which itself accounts for nested objects.

### CODE REVIEW

**Comment by voinik** [comment]
Hey there! It seems that your change fixes the issue. Hope it gets merged!

**Review by bluebill1049 — APPROVED** [review]

**Comment by alex-drakos** [comment]
@cj-young @bluebill1049 I believe this breaks the error.message from being a `string | undefined` to being `string | FieldError | Merge<FieldError, FieldErrorsImpl<any>> | undefined`. 
This causes issues when trying to access the error.message to display it and throws TS errors (which are not app errors as the actual message is always string if there)

**Comment by cj-young** [comment]
Sorry I introduced a bug, I didn't consider that the dot syntax can't index into the error type.
I looked into it a bit more, and I think something similar to this might be able to work:
```ts
error?: PathValue<FieldErrors<TFieldValues>, TFieldName>;
```
but TS is throwing errors about circular references and `TFieldName` not being a valid path for `FieldErrors<TFieldValues>`, so it doesn't work as is. If the original issue still hasn't been fixed, I'll try to find a working solution later that doesn't break anything if I have time.

**Comment by viveleroi** [comment]
I'd suggest reverting this for the next release because "when I have time" isn't helpful. I'm locking our update to 7.51.4 because this change breaks types for `error.message`.

```
const { error, isTouched } = getFieldState(name, formState)
// 7.54.1
// `error` type is FieldError | undefined
// `error.message` type is string | undefined

// 7.55.1
// `error` type is FieldError | Merge<FieldError, FieldErrorsImpl<any>> | undefined
// `error.message` type is string | FieldError | Merge<FieldError, FieldErrorsImpl<any>> | undefined
``

**Comment by reubenporterjisc** [comment]
We are currently experiencing a TS error as well when accessing `error.message` due to this change.

**Pull request merged**
