### PR TITLE
feature: Ts custom errors

### LINKED ISSUE #4408: Feature request: Add ability to set errors unrelated to inputs
**Is your feature request related to a problem? Please describe.**
This is related to #4356 but more focused on the `setError` function. Right now we can only set errors that relate to a specific input. However, there are many cases where there is an error that doesn't relate to a specific input. A simple example is requiring that a field array have at least one element.

**Describe the solution you'd like**
I would like to expand `setError` or add a new function (perhaps called `setFormError` or something), that allows us to set arbitrary errors that don't need to relate to a specific field. We could have these errors be under a specific key in `formState.errors` or in another part of `formState`.

**Describe alternatives you've considered**
My solution right now is to add hidden inputs and use `setError` to set arbitrary errors on it. This works, but it feels wrong as I'm using an input just for the purpose of settings errors. Its value is meaningless.

### PR DESCRIPTION
**Pull request by bluebill1049**
## Context

To allow custom server error.

```ts
useForm<
  TFieldValues extends FieldValues = FieldValues,
  TContext extends object = object,
  TCustomErrors extends object = object
>()
```

## Usage

```ts
type ServerError = {
  test: string
}

useForm<FormState, {}, ServerError>();

setError('test', { type: '' })
```

## Feature Request

close https://github.com/react-hook-form/react-hook-form/issues/4408

### CODE REVIEW

**Comment by wdfinch** [comment]
Questions: 

1. Would the custom errors be present on `formState.errors`?
2. Now that we have this feature is there any chance we could close out #4356 as well? They are closely related and for consistency it would be great to support the custom errors when using schema validation.

**Comment by bluebill1049** [comment]
> Would the custom errors be present on formState.errors?

Yes, however, still under debate inside the team on whether we should let users take care of `useState` instead within hook form.

**Comment by kotarella1110** [comment]
@wdfinch 

> Now that we have this feature is there any chance we could close out #4356 as well? They are closely related and for consistency it would be great to support the custom errors when using schema validation.

Wouldn't #4356 be solved by using the [`NestedValue`](https://react-hook-form.com/jp/ts/#NestedValue) type?

**Comment by kotarella1110** [comment]
@wdfinch I don't think React Hook Form should take care of the server side.
If you want to customize the error, you can also do so as follows:

```ts
type FormState = {
  name: string
}
type CustomError = {
  test: string
}

const { setError } = useForm<FormState & CustomError>();

setError('test', { type: '' });
```

**Comment by wdfinch** [comment]
Hi @kotarella1110, thanks for the reply. Sorry but I think I'm a bit confused here. This PR was linked in my feature request #4408, so I assumed it added the functionality specified there.

It appears from the notes above that this adds a new generic argument that we can use to specify server errors or arbitrary errors unrelated to specific inputs. Additionally, it expands the `setError` method to support setting these non-input errors and a means to access them via `formState.errors`.  Hence the `setError('test', { type: '' })`. Is this correct or am I missing something?

Therefore, my other question above regarding #4356 was could there be a way to access schema level errors unrelated to inputs as well assuming we are adding this functionality to `setError`. It's not a typescript issue so I don't think `NestedValue` is relevant.

I guess what I and other users are facing is there are some very common errors we would want to have access to that don't relate to a specific input field. A prime example being a field array that requires at least one element. While we can validate this, there are issues with both methods of validation (`setError` and schema-based) when it comes to retrieving the error message. 

For `setError` we can only tie an error to a input so we must choose some input to add the error to or add a hidden input to hold the error.

For schema-based validation, we can do the validation for this, but we cannot get the error message if the error is not associated with an input in the schema. So when presenting the error to the user (you need at least one element in your field array) we have no way to do this easily.

I believe the PR above gives this functionality to `setError` but it seems like since schema validation is fully supported as an alternative, we should have this functionality present in both methods.

**Comment by kotarella1110** [comment]
@wdfinch Thanks for your reply! This PR only changes the type of the TS. It just adds a third Generics (`TCustomErrors`).

> For setError we can only tie an error to an input so we must choose some input to add the error to or add a hidden input to hold the error.

What do you mean?
I think it is possible to register errors other than those related to a specific input with `setError`.

https://codesandbox.io/s/flamboyant-voice-q0ckx?file=/src/App.tsx

**Comment by kotarella1110** [comment]
@wdfinch Is the codesandbox you provided correct?

**Comment by wdfinch** [comment]
@kotarella1110 my bad. I've got a bunch of sandboxes going and I didn't fork properly and overwrote what I had :(. 

I've updated my post above to have the correct link. Here's it again.

https://codesandbox.io/s/stoic-archimedes-85zx4?file=/src/App.js

**Comment by bluebill1049** [comment]
> @kotarella1110 my bad. I've got a bunch of sandboxes going and I didn't fork properly and overwrote what I had :(.
> 
> I've updated my post above to have the correct link. Here's it again.
> 
> https://codesandbox.io/s/stoic-archimedes-85zx4?file=/src/App.js
> 
> So what you'll notice is `formState.isValid` is false initially because we don't have 2 array elements, but `formState.errors` is empty meaning we can't tell the user why the form is invalid. So my hope would be that we could schema errors that don't relate to inputs to `formState.errors`.

hmmm, that's a concern for me, it's making tracking valid even more difficult, I am saying this not just from schema's perspective but build invalidation as well.

**Comment by bluebill1049** [comment]
> @bluebill1049 would it be possible to just forward what the schema outputs somewhere we can access in `formState` and then we can sort through it? So you don't need to try and parse it and whatnot. Not having details on the error is a major issue for using schema validation.

you can build a custom resolver right? which you have access what the schema returned.

**Comment by wdfinch** [comment]
I could but are there rules about what I can pass to errors? Can I just use some arbitrary object? Otherwise, I would need to use redux or context to make the error available. I'm guessing I would need to follow some strict formate for the error object or typescript won't be happy. 

```
const useYupValidationResolver = validationSchema =>
  useCallback(
    async data => {
      try {
        const values = await validationSchema.validate(data, {
          abortEarly: false
        });

        return {
          values,
          errors: {}
        };
      } catch (errors) {
        return {
          values: {},
          errors: errors.inner.reduce(
            (allErrors, currentError) => ({
              ...allErrors,
              [currentError.path]: {
                type: currentError.type ?? "validation",
                message: currentError.message
              }
            }),
            {}
          )
        };
      }
    },
    [validationSchema]
  );
```

**Comment by wdfinch** [comment]
I guess I was hoping this could be built in since it seems like a pretty common need.

> hmmm, that's a concern for me, it's making tracking valid even more difficult, I am saying this not just from schema's perspective but build invalidation as well.

Could you explain why it's difficult? Could we not just add whatever the resolver spits out that doesn't align with an input name to some area in `formState.errors` or `formState.resolverErrors` (a new key)?

**Comment by kepejas** [comment]
hi, any plans to merge this?

**Pull request closed without merging**
