### PR TITLE
Version 7.23.0 (next)

### LINKED ISSUE #7290: issue: FieldPath slows down TypeScript considerably
### Version Number

7.20.1

### Codesandbox/Expo snack

https://codesandbox.io/s/charming-browser-9ujqf?file=/src/App.tsx

### Steps to reproduce

1. Open `App.tsx` in the provided repo link.
2. Change the value of the `name` prop on any of the `<Controller />` to an invalid path.
3. Wait for TS to recognize the mistake.
4. Make further changes.

Typescript will come to a crawl:
- Simple changes will take seconds to process.
- IntelliSense becomes unusable.

### Expected behaviour

Changes shouldn't take multiple seconds to process on complex form data.

The issue seems to be the definition of the `FieldPath` type and similar types like `ArrayPath`.
These types eagerly enumerate all paths of an object type.
The resulting union type becomes excessively big for nested objects containing complex objects like `Date`s.

This could be fixed by lazily evaluating the paths. See [`ts-toolbelt`](https://github.com/millsp/ts-toolbelt)'s [`AutoPath`](https://millsp.github.io/ts-toolbelt/modules/function_autopath.html).

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bluebill1049**
🐷 test coverage for types (#7311)
💻 Feature/avoid omit key name use field array (improve DX) (#7301) 

- [x] add type tests 
- [x] Improve useFieldArray keyName DX

### CODE REVIEW

**Comment by bluebill1049** [comment]
hmmm not sure the API is detected change by extractor, i am going to fix it for now.

**Comment by felixschorer** [comment]
It didn't like the merge, I guess. It probably compares the reports by the letter. Maybe there's an unexpected whitespace after the merge. 😅

**Comment by bluebill1049** [comment]
> It didn't like the merge, I guess. It probably compares the reports by the letter. Maybe there's an unexpected whitespace after the merge. 😅

Screen Shot 2021-12-25 at 5 37 49 pm

is this due to format?

**Comment by bluebill1049** [comment]
```tsx
"api-extractor": "api-extractor run --local",
"api-extractor:build": "yarn build:esm && yarn api-extractor",
```

question: @felixschorer do we need both?

**Comment by felixschorer** [comment]
`api-extractor:build` is just for convenience. Generating the report without a build first is pointless though. It uses the build artefacts to generate the report.

**Comment by bluebill1049** [comment]
cc @felixschorer

**Pull request merged**
