### PR TITLE
export FieldValues, FormStateProxy types from main package

### PR DESCRIPTION
**Pull request by ivkirill**
Solve problem with extra import like
`import { FieldValues, FormStateProxy } from 'react-hook-form/dist/types/form';`

### CODE REVIEW

**Comment by bluebill1049** [comment]
hey @kotarella1110 let me know your thoughts on this PR.

**Review by kotarella1110 — COMMENTED** [review]
@ivkirill I think `FieldValues` ​​and `FormStateProxy` can be exported.
Do we need to export `FieldValue`? Please tell us your use case.

**Comment by ivkirill** [comment]
@kotarella1110 right, i don't use FieldValue, i'll fix PR

**Review by kotarella1110 — APPROVED** [review]
LGTM 💯

**Pull request merged**
