### PR TITLE
working towards isValid

### PR DESCRIPTION
**Pull request by pmaier983**
There are some cypress bugs I was unable to fix because I'm having some issues with npm link... Should be a quick fix though.

### CODE REVIEW

**Comment by bluebill1049** [comment]
let's fix this and get it to merge in @pmaier983 great stuff in here.

**Comment by pmaier983** [comment]
> let's fix this and get it to merge in @pmaier983 great stuff in here.

Whenever i try to rebase and test cypress I hit this issue :/
```
TypeScript error in /Users/phillipmaier/Desktop/Code.nosync/react-hook-form/react-hook-form/app/src/conditionalField.tsx(11,18):
Property 'errors' does not exist on type 'FormStateProxy<{ selectNumber: string; firstName: string; lastName: string; min: string; max: string; notRequired: string; }>'.  TS2339

     9 |     handleSubmit,
    10 |     watch,
  > 11 |     formState: { errors, ...rest },
       |                  ^
    12 |   } = useForm<{
    13 |     selectNumber: string;
    14 |     firstName: string;
```

@bluebill1049 any chance you know why this is happening?

**Comment by bluebill1049** [comment]
> > let's fix this and get it to merge in @pmaier983 great stuff in here.
> 
> Whenever i try to rebase and test cypress I hit this issue :/
> 
> ```
> TypeScript error in /Users/phillipmaier/Desktop/Code.nosync/react-hook-form/react-hook-form/app/src/conditionalField.tsx(11,18):
> Property 'errors' does not exist on type 'FormStateProxy<{ selectNumber: string; firstName: string; lastName: string; min: string; max: string; notRequired: string; }>'.  TS2339
> 
>      9 |     handleSubmit,
>     10 |     watch,
>   > 11 |     formState: { errors, ...rest },
>        |                  ^
>     12 |   } = useForm<{
>     13 |     selectNumber: string;
>     14 |     firstName: string;
> ```
> 
> @bluebill1049 any chance you know why this is happening?

hmm you didn't check out from master :( i couldn't check your branch

**Comment by bluebill1049** [comment]
@pmaier983 do a merge, see if that fix it.

**Comment by bluebill1049** [comment]
or we can merge it in as well and i will investigate tonight.

**Comment by pmaier983** [comment]
the error shows up if I just pull `convert-formState-to-useState` and try to start the app locally

**Comment by bluebill1049** [comment]
let's get it in :)

**Pull request merged**
