### PR TITLE
Resolve async pkg dep of cypress to patch ver

### PR DESCRIPTION
**Pull request by Moshyfawn**
| high          | Prototype Pollution in async             |
|---------------|------------------------------------------|
| Package       | async                                    |
| Patched in    | >=3.2.2                                  |
| Dependency of | cypress                                  |
| Path          | cypress > getos > async                  |
| More info     | https://www.npmjs.com/advisories/1070207 |

### CODE REVIEW

**Comment by Moshyfawn** [comment]
Oooops :P Thx for the fix

**Comment by Moshyfawn** [comment]
Ah, might've been the merge

**Comment by Moshyfawn** [comment]
Hm, @bluebill1049, do you need to tweak the workflows to avoid expecting `bindlesize`?
image

**Comment by bluebill1049** [comment]
I was my bad for the merge conflict l.

**Pull request merged**
