### PR TITLE
Feature/reset omit state update

### PR DESCRIPTION
**Pull request by bluebill1049**
This feature allow you to reset the form value without reset the `formState`

`reset({}, { dirty, touched })`

### CODE REVIEW

**Comment by kiansenggoh** [comment]
we will love this feature!

**Review by GohKianSeng — DISMISSED** [review]
nice!!

**Review by cubase — APPROVED** [review]

**Comment by Paquan** [comment]
This would be awesome!
If I understand right than we would have the option to reset maybe formState.dirty when the form gots submitted, right?

**Comment by bluebill1049** [comment]
> This would be awesome!
> If I understand it right we would have the option to reset e.g. formState.dirty when the form gots submitted, right?

That's correct. you can omit state individually.

**Comment by kiansenggoh** [comment]
When will the changed be implemented? Since there is an option for user to choose if they wan to clear the state, why still need up vote?

**Comment by krnlde** [comment]
Ouuh, I could also make use of that feature. Right now I worked around it big time :D

**Comment by kiansenggoh** [comment]
Hi KrnIde

Your workaround is using setValue?

**Comment by bluebill1049** [comment]
> When will the changed be implemented? Since there is an option for user to choose if they wan to clear the state, why still need up vote?

Thanks for your feedback. It's always easy for me to introduce more code into the lib to fulfil users' feature request. However what you desire to have may not be the case for others, hence i tagged as `waiting for up vote`. React Hook Form is great in eyes because it's simplicity and size. That's also the reason i am hesitate to bring more features which potential can have a work around or simply not valuable for others. This lib is not build for **you** or **myself**, it's an open source for everyone, hence everything goes into it need careful thoughts and deserve a voice from everyone. I can see a lot of people want this feature, so i will merge this it most likely this weekend and publish.

**Comment by krnlde** [comment]
> Hi KrnIde
> 
> Your workaround is using setValue?

Partly, but mostly by just avoiding the reset process :D

**Comment by bluebill1049** [comment]
Thanks for everyone's vote. I will update the doc and publish this feature this weekend. Thanks for your patient. 🙏

**Comment by Paquan** [comment]
Thanks. Feels like getting presents :D

**Pull request merged**
