### PR TITLE
fix(useForm): leave formState flags in a consistent state when throwing in handleSubmit onValid

### PR DESCRIPTION
**Pull request by anonkey**
## Proposed Changes

onValid function given to handleSubmit from useForm is often the way to send request to server but when this function throw it leave isSubmitting flag true and isSubmitted flag on false what is inconsistent.

This change keep the current behavior of bubbling up the error but fix the inconsistent formState 

Fixes [#11084](https://github.com/react-hook-form/react-hook-form/issues/11084)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by anonkey** [comment]
Had problem to run 
pnpm tsd and pnpm e2e
Hope this will be checked by CI

**Comment by bluebill1049** [comment]
thanks for the PR, i think this is what i had before but users complain about errors being swallowed by handleSubmit.

**Comment by anonkey** [comment]
Since error are not swallowed like before, is there any chance to have this MR merged ?

**Review by bluebill1049 — APPROVED** [review]
LGTM. let me know if you are happy with this as well @Moshyfawn

**Comment by Moshyfawn** [comment]
This is fine as a behaviour fix 👍

**Comment by Moshyfawn** [comment]
> LGTM. let me know if you are happy with this as well @Moshyfawn

This is fine as a behaviour fix 👍

**Review by Moshyfawn — APPROVED** [review]

**Comment by anonkey** [comment]
Thanks a lot for the PR and for your work

**Comment by pianomansam** [comment]
When will this get released?

Pardon my ignorance, as I'm a user of the project and not yet a contributor. I stumbled across this issue because I'm experiencing isSubmitting still being true after a rejected promise in the onSubmit handler.

**Pull request merged**
