### PR TITLE
React hooks rules

### PR DESCRIPTION
**Pull request by barrymay**
This seems to be working -  please try it out :)

### CODE REVIEW

**Comment by bluebill1049** [comment]
dame you beat me on it lol

**Comment by bluebill1049** [comment]
thanks heaps @barrymay again ❤️ get this bad boy in.

**Comment by barrymay** [comment]
hahah.  I was inspired by the challenge!  The major change I made was to split out the setFields into a function that doesn't validate , and only have the outer function allow the validation step ;)

**Comment by barrymay** [comment]
Please do test your own apps on it - I consider it a big change, but assuming it all works, it should be a good one - @chrisparton1991  please do test this too!

**Comment by bluebill1049** [comment]
yea thanks @barrymay I am testing it with apps

**Comment by bluebill1049** [comment]
here is a beta version `3.19.2-beta.1` if you want to install as `node_module`

**Comment by bluebill1049** [comment]
@barrymay FYI I am planning to write some automation test for this lib, less manual testing.

**Comment by barrymay** [comment]
The more automation the merrier for sure!

Suggestions:  cypress or more unit tests using React-testing-library is a great idea 😊

**Comment by bluebill1049** [comment]
yea I am going to use cypress 👍 I think my unit test is not there for sure, need to revisit them as a whole (especially around the hook).

**Comment by barrymay** [comment]
Super!

**Comment by chrisparton1991** [comment]
Thanks for this, `3.19.2-beta.1` is working perfectly for me 🎉

**Comment by bluebill1049** [comment]
thanks @chrisparton1991 for your testing, looks good on my end too. will publish this baby 👍

**Comment by barrymay** [comment]
sweet  - happy to see this one happen  🎉

**Pull request merged**
