### PR TITLE
[Feature Request] Make useController save to return undefined if no c…

### PR DESCRIPTION
**Pull request by dohomi**
…ontext or control present

Skip initialization of useController if no control or context is present. This is an attempt to solve https://github.com/react-hook-form/react-hook-form/issues/4033

The main use case would be, that users can use the hook inside of their custom component and the functionality will be silently ignored in case its not needed.

### CODE REVIEW

**Comment by bluebill1049** [comment]
Thanks for the PR, however, i don't think this is going to be type-safe for what `useController` returns.

**Comment by dohomi** [comment]
@bluebill1049 the `useFormContext` works in the way that it returns undefined/null if no context is given. It would be ideal if `useController` could do the same, at least I get the feeling that people would expect that it works in the same way.

**Comment by bluebill1049** [comment]
I know what do you mean, but It's case by case.

**Comment by matinzd** [comment]
Any updates?!

**Pull request closed without merging**
