### PR TITLE
remove validation fields

### PR DESCRIPTION
**Pull request by bluebill1049**
This API is pretty useless to consider we have `unregister` API which is more declarative. 

Please use `unregister` in your app instead.

### CODE REVIEW

**Comment by JeromeDeLeon** [comment]
Can we include it in the documentation or something in the release that this API is deprecated?

**Comment by bluebill1049** [comment]
Thanks, @JeromeDeLeon hmmm,  good point but I don't think anyone is using it... But I will make sure to include that in the release note. (not a breaking change, I will do a migrate guide to use unregister instead)

**Comment by JeromeDeLeon** [comment]
No worries, more like another section like `Removed API` even if no one uses it :smiley:

**Comment by bluebill1049** [comment]
sounds good

**Pull request merged**
