### PR TITLE
improve ErrorMessage type

### PR DESCRIPTION
**Pull request by kotarella1110**

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks @kotarella1110 🙏 much cleaner

**Comment by kotarella1110** [comment]
@bluebill1049 Should util functions be impose? Or do you want to leave it as is?

**Comment by bluebill1049** [comment]
you mean export util functions? I think we should export less, only export unnecessary things.

**Comment by kotarella1110** [comment]
I used to export only `get` function for ErrorMessage component, but I will remove this.

**Comment by bluebill1049** [comment]
thanks @kotarella1110

**Pull request merged**
