### PR TITLE
🐞 fix unset nested array object

### PR DESCRIPTION
**Pull request by euphocat**
Hello ! I've noticed a strange behavior while working with form errors. I spotted a problem in the `unset` method. I think my fix might be a bit dirty... But I'm not confortable with that `unset` method (with that while loop and stuff).

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks for the PR, can you demonstrate us with the issue in a codesandbox?

**Comment by euphocat** [comment]
hum maybe I can, but I think it's a bit tricky... isn't the test enough? :)

**Comment by bluebill1049** [comment]
Thanks @euphocat 👍 @kotarella1110 can you please review the change, I think the last refactor break this.

**Comment by euphocat** [comment]
Ok because it's fun, I was able to reproduce it with a bit of my setting: https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-8dbws
It uses io-ts, and call `trigger`

**Comment by bluebill1049** [comment]
thanks @euphocat 👍

**Comment by keiya01** [comment]
Thank you @euphocat for sending PR.
Did this problem occur by executing `trigger()`? If so, I think you might want to write test about this problem with `trigger()`.

**Review by keiya01 — APPROVED** [review]
LGTM!

**Comment by euphocat** [comment]
Thank you for your help and reactivity !

**Comment by bluebill1049** [comment]
Thank you for your reporting and PR @euphocat 🙏

**Pull request merged**
