### PR TITLE
improve setValue type

### PR DESCRIPTION
**Pull request by kotarella1110**
improved type to support nest object 👍 

```ts
type FormValues = {
  string: string;
  number: number;
  object: {
    number: number;
    boolean: boolean;
  };
  array: {
    string: string;
    boolean: boolean;
  }[];
};

const { setValue } = useForm<FormValues>()

setValue('string', 'test')
// function setValue<"string", string>(name: "string", value: string, shouldValidate?: boolean | undefined): void
setValue('number', 1)
// function setValue<"number", number>(name: "number", value: number, shouldValidate?: boolean | undefined): void
setValue('number', 'error')
// ❌: type error
setValue([{ string: 'test' }])
// function setValue<"string">(namesWithValue: DeepPartial<Pick<FormValues, "string">>[], shouldValidate?: boolean | undefined): void
setValue([{ number: 'error' }])
// ❌: type error
setValue([{
  string: 'test',
  number: 1
}])
// function setValue<"string" | "number">(namesWithValue: DeepPartial<Pick<FormValues, "string" | "number">>[], shouldValidate?: boolean | undefined): void
setValue([
  { string: 'test' },
  { number: 1 },
])
// function setValue<"string" | "number">(namesWithValue: DeepPartial<Pick<FormValues, "string" | "number">>[], shouldValidate?: boolean | undefined): void
setValue('object', { number: 1 });
// function setValue<"object", { number: number }>(name: "object", value: DeepPartial<{ number: number; boolean: boolean }>, shouldValidate?: boolean | undefined): void
setValue('object.boolean', true);
// function setValue<"object.boolean", boolean>(name: "object.boolean", value: boolean, shouldValidate?: boolean | undefined): void
setValue('array', [{ string: 'test' }])
// function setValue<"array", { string: string; }[]>(name: "array", value?: (DeepPartial<{ string: string; boolean: boolean; }> | undefined)[] | undefined, shouldValidate?: boolean | undefined): void
setValue('array[1].boolean', true)
// function setValue<"array[1].boolean", boolean>(name: "array[1].boolean", value: boolean, shouldValidate?: boolean | undefined): void
setValue('array[1].boolean', 'noerror')
// function setValue<"array[1].boolean", string>(name: "array[1].boolean", value: string, shouldValidate?: boolean | undefined): void
setValue<string, boolean>('array[1].boolean', 'error')
// ❌: type error
setValue([{ array: [{ boolean: false }]}])
// function setValue<"array">(namesWithValue: DeepPartial<Pick<FormValues, "array">>[], shouldValidate?: boolean | undefined): void
```

### CODE REVIEW

**Comment by bluebill1049** [comment]
exciting for this TS enhancement.

**Comment by kotarella1110** [comment]
Launching the e2e test app (`yarn start:app`) caused the following unexplained error :boom::

スクリーンショット 2020-04-17 0 33 47

This error was caused by passing the `control` prop of the Controller component and useFieldArray.
I spent a lot of time fixing this...
This was solved by simply changing the order of setValues ​​defined in the control type overload :sweat:
I'm not sure why the error caused, but I just solved the issue by changing the order as follows:

https://github.com/react-hook-form/react-hook-form/pull/1412/commits/78884b5d87730c5a1063705ca03c016155aa631f#diff-41df78d86ed4de80aae9b0b9560feb2bR269-L279

Very very very strange... :fearful:
Seems like a TypeScript bug.
I'm glad I could avoid the error :hand:

**Comment by kotarella1110** [comment]
@bluebill1049 `setValue` and `watch` have two generic arguments. Should `getValue` also have two arguments to match this (ex: `getValues<string, boolean>('key3.key2')`)?

https://github.com/react-hook-form/react-hook-form/pull/1328#issuecomment-612909896

**Comment by bluebill1049** [comment]
> Launching the e2e test app (`yarn start:app`) caused the following unexplained error 💥:
> 
> スクリーンショット 2020-04-17 0 33 47
> 
> This error was caused by passing the `control` prop of the Controller component and useFieldArray.
> I spent a lot of time fixing this...
> This was solved by simply changing the order of setValues ​​defined in the control type overload 😓
> I'm not sure why the error caused, but I just avoided it by changing the order as follows:
> 
> [78884b5](https://github.com/react-hook-form/react-hook-form/commit/78884b5d87730c5a1063705ca03c016155aa631f)
> 
> Very very very strange... 😨
> Seems like a TypeScript bug.
> I'm glad I could avoid the error ✋

WOW, that's really strange! and you work it out 👯

**Comment by bluebill1049** [comment]
> @bluebill1049 `setValue` and `watch` have two generic arguments. Should `getValue` also have two arguments to match this ? (ex: `getValues<string, boolean>('key3.key2')`)
> 
> [#1328 (comment)](https://github.com/react-hook-form/react-hook-form/pull/1328#issuecomment-612909896)

I think it make sense to keep them consistent 👍

**Comment by kotarella1110** [comment]
> > @bluebill1049 `setValue` and `watch` have two generic arguments. Should `getValue` also have two arguments to match this ? (ex: `getValues<string, boolean>('key3.key2')`)
> > [#1328 (comment)](https://github.com/react-hook-form/react-hook-form/pull/1328#issuecomment-612909896)
> 
> I think it make sense to keep them consistent 👍

@bluebill1049 Should this create sepalate PR? Or should I commit this improvement to this branch?

**Comment by bluebill1049** [comment]
let's do a separate PR and we can merge this boy in first : )

**Comment by kotarella1110** [comment]
hahaha. Also the same error was triggered 💥

**Pull request merged**
