### PR TITLE
[WIP]: Fix FieldErrors

### LINKED ISSUE #987: Typescript: The property 'message' doesn't exists in 'FieldError | FieldErrors<any>[]'
**Describe the bug**

The property 'message' doesn't exists in 'FieldError | FieldErrors<any>[]'.
The property 'message' doesn't exists in type 'FieldErrors<any>[]'.ts(2339)

This happens in typescript when trying to access errors messages from Autocomplete component from yup validation schema

**Codesandbox link**

Look at line 48!!!

https://codesandbox.io/s/material-demo-o15mc

**Screenshots**

image

### PR DESCRIPTION
**Pull request by stramel**
Fixes #987 

Would like to remove the `| FieldValues` or figure out why `{}` doesn't work without it.

### CODE REVIEW

**Comment by stramel** [comment]
Not really ready for review, just seeing if that fixes CSB

**Comment by bluebill1049** [comment]
@stramel any chance we can solve this issue in the next couple of weeks?

**Comment by stramel** [comment]
@bluebill1049 hopefully. Sorry I'm on a code push for work currently. Hoping to get back to this soon

**Comment by bluebill1049** [comment]
hey @stramel if you are busy, any chance @kotarella1110 can help on this PR. since you guys r the TS guru here.

**Comment by stramel** [comment]
Closing in favor of @kotarella1110's PR #1178

**Pull request closed without merging**
