### PR TITLE
fix: useForm should return a new object on formState changes

### LINKED ISSUE #12423: issue: useForm shouldn't return the same object - react-complier/memo issue
### Version Number

7.53.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/thirsty-keller-zdcy4q

### Steps to reproduce

1. Open https://codesandbox.io/p/sandbox/thirsty-keller-zdcy4q
2. Enter something to age  like 999
3. See that no validation error is shown

Or see 
https://next-15-form-git-main-miklosfazekas.vercel.app

Which has 3 forms:
1. Default ShadCN form - [src](https://github.com/mfazekas/next-15-form/blob/main/app/profile-form.tsx)
2. Default ShadCN form with react compiler disabled - [src](https://github.com/mfazekas/next-15-form/blob/main/app/profile-form-no-rc.tsx)
3. Default ShadCN form and forcing new object form form  - [src](https://github.com/mfazekas/next-15-form/blob/main/app/profile-form-workaround.tsx)

image

### Expected behaviour

Validation error should be shown

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mfazekas**
Fixes: #12423

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]

**Comment by Ganbin** [comment]
Any ETA on the next release that will contain the fix?

**Comment by kelkes** [comment]
How is that a fix? It's a breaking change that crashed almost all of my applications :)

**Comment by cahilfoley** [comment]
Also landed here because this update broke every form in our application (forms being used in effects etc), this probably should have been a breaking change.

**Comment by controversial** [comment]
This was a large breaking change for our application as well.

**Comment by pablo-psi** [comment]
If anyone was doing form validation like this before:

```tsx
const formMethods = useForm()

formMethods.trigger().then(() => {
    if(formMethods.formState.isValid) {
        // ...
    }
})
```

After upgrading react-hook-form, better do it like this (fixed newly introduced validation bugs for me):

```tsx
const formMethods = useForm()

formMethods.trigger().then((isValid) => {
    if(isValid) {
        // ...
    }
})
```

**Pull request merged**
