### PR TITLE
Better type hints for .watch and .unregister of useForm instance

### LINKED ISSUE #159: Better Type Hints for useForm(..).watch and .unregister's fieldName arguments
The types definitions for `.watch` and `.unregister` functions in the **useForm.d.ts** file look something like:

```
    // ...
    unregister(name: string | string[]) => void;
    // ...
    watch: (fieldNames?: string | string[], ...
    // ...
```

These two arguments with types `string | string[]` are the ones I'm requesting an improvement for.

Just like clearError, setValue or most of the other methods in this file, it is possible to add the generic `Name | Name[]` type to them.

I understand that the reasoning behind making them of a `string | string []` type is so that it could be possible to watch or unregister nested and/or array filed names. 

However, doing something like this (👇) would me a much nicer DX (as most IDEs could provide auto complete hints for most of these field names):

```
    // ...
    unregister(name: Name | string | (Name | string)[]) => void;
    // ...
    watch: (fieldNames?: Name | string | (Name | string)[], ...
    // ...
```

I also understand that this change won't add much to static type checking (because `string` is a more general type than `Name`). But it provides Hints in IDEs.

***Additional (Probably Impossible) Request:***

*I'm not exactly sure how (or if it's even possible), but if it is possible to be specific enough with the type to remove string and also support arrays and nested fields, strictly with the correct type, it would be super nice. (¯\\\_(ツ)\_/¯ I know this is a little too far fetched).*

### PR DESCRIPTION
**Pull request by kaleabmelkie**
Fixes #159 

## Proposed Changes

  - Enhance field `name` arguments type of `.watch` and `.unregister` (in `useForm`) from `string | string[]` to `Name | string | (Name | string)[]`. This provides better auto-complete hints in IDEs for most field names (with the exception of individual array and nested field names).

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks @kaleabmelkie for the quick PR, @stramel and @barrymay you guys want to have 👁 over this?

**Comment by stramel** [comment]
LGTM. I'm still planning on trying to clean up the typings. I would like to avoid the weird castings but I need to look up a few things.

**Comment by bluebill1049** [comment]
cool let's merge this one in first and sort it after @stramel I think its an improvement for now?

**Comment by stramel** [comment]
Yes, I should be an improvement for now

**Comment by bluebill1049** [comment]
@kaleabmelkie could you please resolve the conflict? we will get this one out in the next release

**Comment by barrymay** [comment]
@stramel on your comment
> LGTM. I'm still planning on trying to clean up the typings. I would like to avoid the weird castings but I need to look up a few things.

totally agree - I haven't looked into this at all, but I wonder if the strings need to be there at all, what's the case still to not use Name | Name[]?  I look forward to your PR

**Comment by kaleabmelkie** [comment]
@barrymay, I believe just Name | Name[] would be insufficient for nested field names like: form.watch('foo.bar')

**Comment by kaleabmelkie** [comment]
@barrymay, I wonder if something like form.watch('foo.bar') is supported?

(Sorry, I'm new to this library)

If it is not supported, then I believe the string types have no purpose, and it could be just Name | Name[]

**Comment by bluebill1049** [comment]
@kaleabmelkie yes it's supported

**Comment by kaleabmelkie** [comment]
Then I think that the strings will be needed.

I'll try to resolve the merge conflicts now.

**Comment by kaleabmelkie** [comment]
@bluebill1049, I believe it's ready now.

**Comment by bluebill1049** [comment]
thank you @kaleabmelkie

**Comment by bluebill1049** [comment]
could you please do testing for the beta version too? `3.21.1-beta.1` I will test it out too.

**Comment by barrymay** [comment]
@bluebill1049 thanks for the clarity ;)

**Pull request merged**
