### PR TITLE
close #2937 improve unregister behaviour with dirty fields

### LINKED ISSUE #2937: formState is not updated after input unmount
**Describe the bug**
When you delete input, the formState's isDirty is not changing to true
**To Reproduce**

1. Go to the sandbox
2. Notice isDirty === false
3. Click on the delete button
4. Notice isDirty remains false
5. (Optional) You can click on the submit button to ensure that the input's values are removed from the form

**Codesandbox link (Required)**
- https://codesandbox.io/s/amazing-voice-e6339?file=/src/App.js

**Expected behavior**
formState should change after unregistering input

**Additional context**
Using react-hook-form v6.8.2

### PR DESCRIPTION
**Pull request by bluebill1049**
## Description:

improve dirty fields check with unmounted inputs, still should use `useFieldArray` for dynamic inputs. close #2937 

## Change:

- when input unmounts `touched` and `dirtyFields` will no longer get removed from `formState`. 

## Demo:
CSB: https://codesandbox.io/s/happy-leftpad-w6j5k?file=/src/App.js:387-388

### CODE REVIEW

**Comment by stephane439** [comment]
Hey good job

**Comment by bluebill1049** [comment]
> Hey good job

thanks ❤️

**Comment by keiya01** [comment]
Sorry that I could not review 😩

**Comment by bluebill1049** [comment]
> Sorry that I could not review 😩

no worries at all 👍 though you must be busy anyhow. ❤️

**Pull request merged**
