### PR TITLE
changed `errors` to `formState: { errors }`

### PR DESCRIPTION
**Pull request by amantiwari1**
It made me confused about getting errors in my project. i figured out to fix it, this example got wrong in useForm. I managed to changed it to avoid confused to anyone 
this is my first pull request to popular open source. i hope merge it after review

### CODE REVIEW

**Comment by bluebill1049** [comment]
oops forgot to update that one.

**Comment by bluebill1049** [comment]
thanks

**Comment by AhmedSarhan** [comment]
hello since the update now the errors aren't dynamic, before then I used to get errors in the ui then they clear themselves under the hood when I type a new value or something like this ... now this doesn't happen

**Comment by bluebill1049** [comment]
> hello since the update now the errors aren't dynamic, before then I used to get errors in the ui then they clear themselves under the hood when I type a new value or something like this ... now this doesn't happen

please send a detailed question at discussion and provide a codesandbox.

**Pull request merged**
