### PR TITLE
chore: upgrade prettier and eslint plugins

### PR DESCRIPTION
**Pull request by abnud11**
This PR upgrades all ESLint plugins to the latest version, since `eslint-plugin-prettier` v5(the new version) has a peer dependency on prettier v3, I had to upgrade prettier too.

The main changes are in these files:
`package.json`
`pnpm-lock.yaml`
`.eslintrc`

All other file changes are the result of automatic `pnpm lint:fix` command(most of them are related to the upgrade of `prettier` to v3).

### Warning
Don't forget to restart vscode after this PR, you'll get false errors if you don't do this(or from command palette restart ESLint server).

### CODE REVIEW

**Review by bluebill1049 — DISMISSED** [review]
LGTM! later on the stage, i think we will consider to move to biomejs.

**Comment by bluebill1049** [comment]
could you resolve the conflict plz? thanks

**Comment by abnud11** [comment]
> could you resolve the conflict plz? thanks

conflicts resolved

**Review by bluebill1049 — APPROVED** [review]
thank you! LGTM

**Pull request merged**
