### PR TITLE
stricter type check on onChange event type

### PR DESCRIPTION
**Pull request by Newbie012**

### CODE REVIEW

**Comment by Newbie012** [comment]
@bluebill1049 If I change it to

```ts
export type ChangeHandler = (event: {
  target: {
    name: string;
    value?: unknown;
    type?: unknown;
  };
  type?: any;
}) => Promise<void | boolean>;
```
then the build will pass. Although, I have a feeling that the fix has bubbled up potential bugs. What do you think?

**Comment by bluebill1049** [comment]
yea... let's leave as it is for now, shall we?

**Comment by Newbie012** [comment]
@bluebill1049 It's probably not perfect, but I believe it's better than the current implementation of `ChangeHandler`. But I guess it's up to you :)

**Comment by bluebill1049** [comment]
Thanks, I am worried this may introduce breaking changes to existing users. Let's skip this one for now. 👍

**Comment by bluebill1049** [comment]
thanks for the PR.

**Comment by bluebill1049** [comment]
actually, let's roll with this if any issues coming from this PR we can looking further for solutions.

**Comment by bluebill1049** [comment]
looks like it breaks for RN.

**Comment by Newbie012** [comment]
@bluebill1049 I haven't dug deeper into the project, but I have managed to create a prototype that:

 - works both on react-dom and react-native
 - better type safety
 - type inference

Check it here - https://codesandbox.io/s/modern-shadow-0rj3o?file=/src/App.tsx

image
image

**Comment by bluebill1049** [comment]
oh, nice! feel free to send another PR! that's awesome. Thanks.

**Comment by Newbie012** [comment]
I'm afraid it would cause breaking changes

**Comment by bluebill1049** [comment]
ok than, thanks for the investigation and perhaps we can look into this again in the next major version.

**Pull request merged**
