### PR TITLE
Adding basic formspree example

### PR DESCRIPTION
**Pull request by colevscode**
This does the minimum needed to set up a backend using Formspree:

1. Disables the submit button while waiting for a response.
2. Does basic server side validation and shows errors. (just checks to ensure the form is live, and there is a valid email address)
3. If successful, replaces the form with a "thanks" message.

Formspree docs here: https://help.formspree.io/hc/en-us/articles/360055613373-The-Formspree-React-library

### CODE REVIEW

**Comment by colevscode** [comment]
**Size Change:** 0 B 

**Total Size:** 96 kB


<details><summary>ℹ️ <strong>View Unchanged</strong></summary>

| Filename | Size | Change | |
|:--- |:---:|:---:|:---:|
| `dist/index.cjs.development.js` | 15.4 kB | 0 B |  |
| `dist/index.cjs.production.min.js` | 9.07 kB | 0 B |  |
| `dist/index.esm.js` | 15.4 kB | 0 B |  |
| `dist/index.ie11.development.js` | 19.6 kB | 0 B |  |
| `dist/index.ie11.js` | 143 B | 0 B |  |
| `dist/index.ie11.production.min.js` | 11.4 kB | 0 B |  |
| `dist/index.js` | 142 B | 0 B |  |
| `dist/index.umd.development.js` | 15.7 kB | 0 B |  |
| `dist/index.umd.production.min.js` | 9.16 kB | 0 B |  |


</details>



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

**Comment by colevscode** [comment]
Not sure how to get the ci/circleci build check to run

However this PR doesn't include any new functionality. It's just documentation

**Comment by colevscode** [comment]
Any feedback? Is this the sorta example you all are interested in?

I'm hoping that this will be useful for the community because it shows how easily one can wire up a form backend to react-hook-form. I was actually surprised at how easy it was.

I realize there are several options for form providers. Obviously I think formspree is a good one, and it's one of the most popular choices out there, with a generous free plan that should be good enough for a lot of personal use cases.

**Comment by bluebill1049** [comment]
Hi @colevscode sorry to get back to you so late, was busy with work and try to resolve issues around hook form and pushing the new minor update. Thanks a lot for the pull request, but I think the examples folder is purely used for hook form API. However, before you close this PR, maybe we should have a section to includes integration with external providers like `formspree`, I will let you know once we are going to have a category, then we can include more providers too.

**Comment by colevscode** [comment]
Yeah makes sense! Happy to help out if I can. What do you mean by a category? Like in the examples section?

**Comment by bluebill1049** [comment]
Yes, we have a new section with external providers section, I will follow you up.

**Comment by colevscode** [comment]
where can I find the new section for external providers?

**Pull request closed without merging**
