### PR TITLE
pnpm

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by Moshyfawn** [comment]
Do you seen any benefits in moving this poly-repo to pnpm?

**Comment by bluebill1049** [comment]
faster @Moshyfawn but I got too tired at night :(

**Comment by jsun969** [comment]
I love this but why it's closed 😳

**Comment by bluebill1049** [comment]
> I love this but why it's closed 😳

couldn't have time for it, want to give it a try and send a pr?

**Comment by jsun969** [comment]
I'd like to but I'm too busy these days. Maybe I can try it on my winter vacation.
btw, notice some ci tools(e.g. https://github.com/dependabot/dependabot-core/issues/1736) cannot work properly with pnpm right now

Sry again T_T

**Comment by bluebill1049** [comment]
all good 👍 no worries @jsun969

**Comment by nvh95** [comment]
@bluebill1049 It's super cool that you started experimenting `pnpm`. I can give you a hand. Can you share what struggles are you facing before this PR get closed?

**Comment by bluebill1049** [comment]
Thanks very much @nvh95 for giving a hand.

Screenshot 2022-12-04 at 12 25 31 pm

The difficulties are between in jest config and the rollup config. I haven't got a chance to look closely enough. I gave up quickly on that night, lol.

**Pull request closed without merging**
