### PR TITLE
Add missing OmitResetState form state

### PR DESCRIPTION
**Pull request by GohKianSeng**
Add missing OmitResetState form state

### CODE REVIEW

**Comment by bluebill1049** [comment]
awesome thanks for contributing!

**Comment by kiansenggoh** [comment]
Haha I was about to msg u

**Comment by bluebill1049** [comment]
build failed due to cypress again... i will get it first.

**Comment by yonusbakhshi** [comment]
@GohKianSeng @bluebill1049 How to use this omitResetState ?  I didnt find any example or documentation/. Thanks in advance

**Comment by bluebill1049** [comment]
@yonicalsin take a look at the doc: 
Screen Shot 2020-08-11 at 10 27 19 pm

**Comment by yonusbakhshi** [comment]
@bluebill1049 Thanks for the quick reply! I have already tried this solution here. The problem is, reseting one signle field, would reset the whole form . I am looking to supply OmidResetState but do not know how to .

**Pull request merged**
