### PR TITLE
improve DX of register function for useFieldArray hook

### LINKED ISSUE #1070: [useFieldArray] Improve the DX of register
**Is your feature request related to a problem? Please describe.**
Pulling this improvement discussion out of the previous PRs and into an issue to easily track. See the bottom for related discussions and PRs.

Basically, you can't call `ref={register}` with `useFieldArray`. This is very counter-intuitive based on the fact that the library allows for this syntax in other components/hooks.

**Describe the solution you'd like**
Would like to be able to use `ref={register}`

**Describe alternatives you've considered**
Could remove that syntax entirely. In practice, I'm not sure how much it is used and is only saving a few characters `()`

**Additional context**
https://github.com/react-hook-form/react-hook-form/pull/896#discussion_r370429677
#916 

@kotarella1110 @bluebill1049

### PR DESCRIPTION
**Pull request by kotarella1110**
Fixed to work without passing `register` function as empty arg when using `useFieldArray`.
This improves DX.

old:

```ts
ref={register()}
```

new:

```ts
ref={register}
```

codesandbox: https://codesandbox.io/s/react-hook-form-pr-1106-l3o3b

close #1070

### CODE REVIEW

**Comment by bluebill1049** [comment]
awesome stuff! can you update the automation? see if they will all pass?

**Comment by bluebill1049** [comment]
do a search register() and replace with register :)

**Comment by kotarella1110** [comment]
@bluebill1049 I searched with `register()` but couldn't find it.
What should I do?

**Comment by bluebill1049** [comment]
oh i see because i was doing `ref={register({ required: 'This is required' })}` in the automation app.

**Comment by bluebill1049** [comment]
you want to try to use it at this codesandbox?

**Comment by kotarella1110** [comment]
> oh i see because i was doing `ref={register({ required: 'This is required' })}` in the automation app.

Should I replace `ref={register({ required: 'This is required' })}` with  `register` in the automation app?

**Comment by bluebill1049** [comment]
> > oh i see because i was doing `ref={register({ required: 'This is required' })}` in the automation app.
> 
> Should I replace `ref={register({ required: 'This is required' })}` with `register` in the automation app?

we have some validation rule testing there. unless you want to create a new script. I will test your code with that codesandbox now.

**Comment by bluebill1049** [comment]
wow looks like it's working! https://codesandbox.io/s/react-hook-form-usefieldarray-yt3qc

**Comment by kotarella1110** [comment]
> I will test your code with that codesandbox now.

I understood. Thanks for your testing!

**Comment by bluebill1049** [comment]
wow you nailed this!!! 
Screen Shot 2020-02-27 at 11 19 22 am

how did you work this out???

**Comment by kotarella1110** [comment]
No such error is caused in my environment.

スクリーンショット 2020-02-27 9 24 51

**Comment by bluebill1049** [comment]
it's working! i changed to just `ref={register}` and errors automation is expected.

**Review by bluebill1049 — APPROVED** [review]
how did you work this out?

**Comment by kotarella1110** [comment]
@bluebill1049 I fixed to recreate `register` function when `fields` of `useFieldArray` are updated.

1. Update `watchFieldArrayRef.current` before `fields` are updated using setField.

https://github.com/react-hook-form/react-hook-form/blob/232af81f4c025b14e22242ceb0051cddb58652dc/src/useFieldArray.ts#L60-L64

2. Because I added `watchFieldArrayRef.current` to `useCallback` deps, the `regsiter` function is recreated every time the `fields` are updated.

https://github.com/react-hook-form/react-hook-form/blob/232af81f4c025b14e22242ceb0051cddb58652dc/src/useForm.ts#L1214

Can I merge this PR?

**Comment by bluebill1049** [comment]
it's already approved :) amazing stuff

**Pull request merged**
