### PR TITLE
remove extra object compare logic

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Review by JeromeDeLeon — DISMISSED** [review]
LGTM! This is awesome! :fire:
Great! We don't need to separate it to a file unless this is being used or going to be used elsewhere.
Pretty neat!! :confetti_ball:

**Review by pmaier983 — DISMISSED** [review]
LGTM!

**Comment by JeromeDeLeon** [comment]
Oh, for checking of length, I was thinking this yesterday if its worth checking and decided not to because the objects might be pretty small and `error.types` still got iterated from start to finish.

Also, the placement is incorrect because the objects were already  compared before checking if its worth comparing the two based on there length.

Check the length first, then compare. 😬😬

**Comment by bluebill1049** [comment]
Send a PR😘

**Comment by bluebill1049** [comment]
Maybe worthy to beef up the tests too. So we are more confident.

**Pull request merged**
