### PR TITLE
Add react to external deps

### LINKED ISSUE #10465: issue: Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
### Version Number

7.44.2

### Codesandbox/Expo snack

-

### Steps to reproduce

When I want to build my app on CRA. I got an error
`
Creating an optimized production build...
Failed to compile.
./node_modules/react-hook-form/dist/index.esm.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
`

### Expected behaviour

Build

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Moshyfawn**
Closes: #10465 (maybe lol)

### CODE REVIEW

**Comment by Moshyfawn** [comment]
Uh, where's this feature where it bundles a package & serves it from a codesandbox, so it can be used as a CDN for packages to try out..

**Comment by Moshyfawn** [comment]
@bluebill1049 can we try this one? I'm not sure why I can't PR preview the package at this time

**Comment by bluebill1049** [comment]
> Uh, where's this feature where it bundles a package & serves it from a codesandbox, so it can be used as a CDN for packages to try out..

Not sure, I haven't touch change that. :(

**Comment by bluebill1049** [comment]
> @bluebill1049 can we try this one? I'm not sure why I can't PR preview the package at this time without actually releasing a version

I can try to release a beta version

**Comment by Moshyfawn** [comment]
> I can try to release a beta version

It'd be great, if you can!

**Comment by bluebill1049** [comment]
`7.44.3-beta.0` published

**Comment by Moshyfawn** [comment]
Uh, nope, it didn't do it. Altho, I'm not sure I'm using the correct rollup external deps API..

**Comment by Moshyfawn** [comment]
Can we try once again? Sorry, I'm not sure how to avoid bothering you in this situation

**Comment by bluebill1049** [comment]
> 

That's all good, i have been lazy to setup changeset which I should.

**Comment by bluebill1049** [comment]
published

**Comment by Moshyfawn** [comment]
Nah, didn't do anything

**Comment by bluebill1049** [comment]
I reckon it's gotta do with one of the dependencies for the build tool.

**Comment by Moshyfawn** [comment]
Might be. Bundler issues are the worst! 🤭

I've also been reading up on[ these PRs](https://github.com/formatjs/formatjs/pull/1407) that apparently fix Webpack compatibility, but not sure. There was a report of someone having the same issue with Next.js, which does use Webpack too

**Comment by Moshyfawn** [comment]
@bluebill1049 I found it and fixed. Will fix this PR & push

**Pull request closed without merging**
