### PR TITLE
feat: make UseFormRegisterReturn generic over TFieldName

### PR DESCRIPTION
**Pull request by omjadas**
Improve the type for `UseFormRegisterReturn.name`

### CODE REVIEW

**Comment by Moshyfawn** [comment]
What's the use-case for this feature?

**Comment by omjadas** [comment]
> What's the use-case for this feature?

In my case, I have a custom component that acts as a wrapper for an `<input />` and I want to pass the name of the field and a corresponding control to that component so that I can use `useWatch` inside of it. Something like the following simplified example.

```tsx
import { Control, FieldPath, useForm, useWatch } from "../../../../react-hook-form";

interface MyInputProps<T extends string, U> extends React.HTMLProps<HTMLInputElement> {
  name: T,
  control: Control<U, any>,
}

const MyInput = <T extends FieldPath<U>, U extends Record<string, any>>(
  {
    name,
    control,
    ...props
  }: MyInputProps<T, U>,
): JSX.Element => {
  const value = useWatch({ name, control });

  // use value

  return (
    <input
      name={name}
      {...props}
    />
  );
};

interface Form {
  email: string,
}

const MyForm: React.FC = () => {
  const {
    register,
    control,
  } = useForm<Form>();

  return (
    <form>
      <MyInput
        control={control}
        {...register("email")}
      />
    </form>
  );
};
```

**Comment by bluebill1049** [comment]
Thanks for the PR, this is actually intended to keep the name as `string` without impact ts error with the `name` type.

**Comment by omjadas** [comment]
> Thanks for the PR, this is actually intended to keep the name as `string` without impact ts error with the `name` type.

Sorry, I'm not sure if I understand your comment. Are you saying that you would prefer to keep the name as a string instead of making it generic?

**Comment by bluebill1049** [comment]
Yea, as this would lead to a breaking change to the existing user's controlled component when their child component accepts name as `string` instead of `FieldPath`

**Comment by omjadas** [comment]
I don't think that should be an issue, the actual type of name will end up being a string literal type (in the case of my example `"email"`), which is a subtype of `string`, so can still be passed to a component that accepts name as `string`. The reason I used `FieldPath` in my example was to allow the name and control to be passed to `useWatch`.

**Comment by omjadas** [comment]
As an example, the following also works

```tsx
import { useForm } from "react-hook-form";

interface MyInputProps extends React.HTMLProps<HTMLInputElement> {
  name: string,
}

const MyInput: React.FC<MyInputProps> = (
  {
    name,
    ...props
  },
): JSX.Element => {
  return (
    <input
      name={name}
      {...props}
    />
  );
};

interface Form {
  email: string,
}

const MyForm: React.FC = () => {
  const {
    register,
  } = useForm<Form>();

  return (
    <form>
      <MyInput
        {...register("email")}
      />
    </form>
  );
};
```

**Comment by Moshyfawn** [comment]
Hm.. I see your point.

There's an ongoing development of the next major v8 RHF is happening. The goal is to improve on the existing type-safety of the package.

On of the improvements is to bring [the branded strings](#7354) into RHF, which would allow for a better DX around building reusable inputs.

Do you thing this is something can help you with your use-case?

**Comment by omjadas** [comment]
> Hm.. I see your point.
> 
> There's an ongoing development of the next major v8 RHF happening. The goal is to improve on the existing type-safety of the package.
> 
> On of the improvements is to bring [the branded strings](https://github.com/react-hook-form/react-hook-form/discussions/7354) into RHF, which would allow for a better DX around building reusable inputs.
> 
> Do you thing this is something can help you with your use-case?

I think if the type of `UseFormRegisterReturn.name` was changed to `PathWithMeta` and `useWatch` was updated to support it, then it would work.

**Review by bluebill1049 — DISMISSED** [review]

**Comment by bluebill1049** [comment]
@omjadas could you please resolve the conflict?

**Review by kotarella1110 — APPROVED** [review]
> I don't think that should be an issue, the actual type of name will end up being a string literal type (in the case of my example `"email"`), which is a subtype of `string`, so can still be passed to a component that accepts name as `string`.

This is correct 👍🏻 
As far as I can think, this change will have no impact on users.

LGTM 🎉

**Comment by bluebill1049** [comment]
thanks for the confirmation and double check @kotarella1110 🙏

**Pull request merged**
