### PR TITLE
fix: Solve the issue of race condition with resolver.

### PR DESCRIPTION
**Pull request by mehunk**
#10989

### CODE REVIEW

**Comment by bluebill1049** [comment]
could provide some unit tests plz? thanks in advance

**Comment by bluebill1049** [comment]
thank you, will review it soon.

**Review by bluebill1049 — APPROVED** [review]
LGTM

**Comment by bluebill1049** [comment]
This test passes even with the code change. 🥲

**Comment by mehunk** [comment]
> This test passes even with the code change. 🥲

How the code change? When I used the not fixed code to test, it failed.

**Comment by bluebill1049** [comment]
Oh maybe I check out the wrong branch. I will double check. Thanks for the PR.

**Comment by mehunk** [comment]
You are welcome! Thank you for this great library!

**Pull request merged**
