### PR TITLE
fix: Unable to setFocus to Controller after reset

### PR DESCRIPTION
**Pull request by Moshyfawn**
Related #7648
[Working CSB example](https://codesandbox.io/s/blissful-haibt-4422r?file=/src/src/useController.ts)

### CODE REVIEW

**Comment by bluebill1049** [comment]
awesome first PR @Moshyfawn thank you 🙏

**Comment by radokristof** [comment]
When this fix will be released?

**Comment by Moshyfawn** [comment]
FYI, @radokristof, it's already out with [7.25.1](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.25.1)

**Comment by radokristof** [comment]
@Moshyfawn thank you, that's great!

**Pull request merged**
