### PR TITLE
type option consistency

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by Moshyfawn** [comment]
Straight into `react-18` branch, not master?

**Comment by bluebill1049** [comment]
> Straight into `react-18` branch, not master?

yep, it's a breaking change.

**Comment by Moshyfawn** [comment]
Just to be super picky 'cuz I just woke up and haven't had my coffee yet lol:
Do you think we should change the wording to include "options" instead of config just for consistency sake in
- `useForm.ts`: "form **options**" instead of "form **configuration**"
- `formState.test.tsx`: "when delay **option** is set" instead of "when delay **config** is set"
- `setValue.test.tsx`: "touched with shouldTouched **option**" instead of "touched with shouldTouched **config**"
image

**Comment by bluebill1049** [comment]
> Just to be super picky 'cuz I just woke up and haven't had my coffee yet lol: Do you think we should change the wording to include "options" instead of config just for consistency sake in
> 
> * `useForm.ts`: "form **options**" instead of "form **configuration**"
> * `formState.test.tsx`: "when delay **option** is set" instead of "when delay **config** is set"
> * `setValue.test.tsx`: "touched with shouldTouched **option**" instead of "touched with shouldTouched **config**"
> 
> image

yea, i will do another PR against master 👍

**Review by Moshyfawn — APPROVED** [review]

**Pull request merged**
