### PR TITLE
Allow keepIsSubmitSuccessful flag

### PR DESCRIPTION
**Pull request by stefanpl**
[This ticket](https://github.com/react-hook-form/react-hook-form/issues/7464) by @ikevinws describes the desired behavior.

**Please note**:
- `lint` will complain about a `"@ts-nocheck"` in `setup.native.ts`
- `cypress` will fail the `setValueAsyncStrictMode.cy.ts` test

Both problems also occur on current `master` and are unrelated to the given change.

Would be sweet to see this merged :)

### CODE REVIEW

**Comment by bluebill1049** [comment]
Thanks for the PR! Let's keep it open for a while since the original feature request demand is not there yet.

> Both problems also occur on current master and are unrelated to the given change.

Yes, will fix that.

**Comment by stefanpl** [comment]
>  since the original feature request demand is not there yet.

Well, on that note: the ticket is closed, and I cannot give it an upvote. I would assume nobody can. Honestly I have no idea why, since I can vote on other closed tickets (e.g. [this one](https://github.com/react-hook-form/react-hook-form/issues/7661)), and it does not seem label- or column-related.
 I'm not too familiar with github ticketing, hope you'll know more 😊
 
 > Let's keep it open for a while

Can't really say I'm thrilled about the ticket not being merged.

On a technical perspective, in my opinion (which of course is very biased), the current API is just inconsistent: why would you have a `keepIsSubmitted` flag, but no `keepIsSubmitSuccessful`? 🤔 

On a process perspective, I was not aware of tickets needing a certain amount of upvotes to be considered for merging. I totally understand that the core team needs to prioritise development time, and that upvotes are a decent metric for this. But if this serves as a hard blocker for merge requests from contributors, I would suggest:

- having two separate columns (instead of a single "pending") in the [project board](https://github.com/react-hook-form/react-hook-form/projects/1): "needs more upvotes" // "ready to go". 
- transparently documenting the process in the `contributing.md`
- of course, making sure tickets can be upvoted at all

This would hopefully keep time efforts and frustration lower on both ends 🙏

**Comment by bluebill1049** [comment]
> having two separate columns (instead of a single "pending") in the [project board](https://github.com/react-hook-form/react-hook-form/projects/1): "needs more upvotes" // "ready to go".

Sounds good to me.

> transparently documenting the process in the contributing.md

Open to suggestions.

**Comment by stefanpl** [comment]
@bluebill1049 sorry to bother, but I feel that you didn't at all reply to a rather important remark from my last comment:

>  the ticket is closed, and I cannot give it an upvote. I would assume nobody can. 

Confirmed this with a colleague, who cannot vote [the ticket](https://github.com/react-hook-form/react-hook-form/issues/7464) either.

Could you please take a look why this is the case? Having tickets in "Needs upvote" when they can't be upvoted it a bit of a dead end 😊

**Comment by bluebill1049** [comment]
looks like the original issue is getting staled, i have unlocked it.

**Comment by stefanpl** [comment]
@bluebill1049 the [feature request](https://github.com/react-hook-form/react-hook-form/issues/7464) has 14 upvotes. How many to a merge? :)

**Comment by dmitry-zaets** [comment]
I couldn't vote for the original issue, but I would love to have this feature merged.
One of the use cases of keeping the result state of the last submission is to show notifications in a declarative way (e.g., with a [Toast from Radix UI](https://www.radix-ui.com/docs/primitives/components/toast)). It would be something like this:
``` tsx
  {!isSubmitting && isSubmitSuccessful && <Toast description="Success" type="success" />}
```

**Comment by stefanpl** [comment]
@dmitry-zaets thanks for your comment.

Not being able to vote on tickets that are waiting for upvotes is pretty much the tragedy of this repo. I cannot say if the team is not fully aware, uor if there's a reason to keep it like this 🤔

Just in case this does not move forward – [patch-package](https://www.npmjs.com/package/patch-package) could be a last resort.

**Comment by matt-greenfield-15** [comment]
I would love to see this merged, where should I add my upvote please @bluebill1049 ? Thanks

**Review by bluebill1049 — DISMISSED** [review]

**Comment by bluebill1049** [comment]
Could you resolve the conflicts plz?

**Review by bluebill1049 — APPROVED** [review]

**Pull request merged**
