### PR TITLE
improved bundle size with production code

### PR DESCRIPTION
**Pull request by keiya01**
I think error message (like `console.warn`) is needed only in development mode. Therefore we need to remove this line with tree shaking.

### CODE REVIEW

**Comment by bluebill1049** [comment]
would be nice if can avoid increate the bundle size 👀

**Comment by keiya01** [comment]
@bluebill1049 
hmmm, do you think about increasing bundle size in development environment.

**Comment by bluebill1049** [comment]
oh, wait you are right! sorry 🙏 let's go ahead with it

**Comment by keiya01** [comment]
Is there code else that is used only in development environment?

**Comment by bluebill1049** [comment]
> Is there code else that is used only in development environment?

don't think so,

**Review by bluebill1049 — APPROVED** [review]
👍

**Pull request merged**
