### PR TITLE
fix controller test is dirty

### PR DESCRIPTION
**Pull request by pierluigigiancola**
the test for the controller that should test that it's dirty was using isTouched and focus + blur instead of isDirty and changing the value

### CODE REVIEW

**Comment by bluebill1049** [comment]
oh nice, could you duplicate the test for touch as well? thanks 👍

**Comment by pierluigigiancola** [comment]
I'm sorry, but I don't understand your request.
The test for touch is already in **controller.test** and it seems okay to me.
Are you suggesting we create a test that asserts whether the input is touched after its value is changed?

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
> I'm sorry, but I don't understand your request. The test for touch is already in **controller.test** and it seems okay to me. Are you suggesting we create a test that asserts whether the input is touched after its value is changed?

That's fine then 👍 thanks for the fix.

**Comment by pierluigigiancola** [comment]
Thanks for the amazing library 😄

**Pull request merged**
