### PR TITLE
improve isValid

### PR DESCRIPTION
**Pull request by bluebill1049**
- validate default value during register phase
- imporve checkbox value check

reference to this issue: https://github.com/react-hook-form/react-hook-form/issues/264

### CODE REVIEW

**Comment by sktt** [comment]
hi @bluebill1049 the problem with passing validation in the first vs second argument. 

https://codesandbox.io/s/crazy-euler-udzz1
I guess you've already seen it though :)

**Comment by bluebill1049** [comment]
@sktt should never in the first argument. 

`register({ name: "test", validate });` This is wrong.

**Comment by sktt** [comment]
oh! ok, then i was decieved by the docs here https://react-hook-form.com/api#register with `ref={register({ validate })}`, I guess the example with custom inputs could demonstrate how to do validation too at some point..

**Comment by bluebill1049** [comment]
@sktt `ref={register({ validate: () => {} })}` is really `register({ validate: () => {} }))(ref)`

**Comment by bluebill1049** [comment]
@sktt u got a chance to test out this PR? I tested it’s working fine for me

**Comment by sktt** [comment]
im looking at it

**Comment by sktt** [comment]
Yes! I just had to restart my cra and it seems to work!
Awesome!

**Pull request merged**
