### PR TITLE
Provide isSubmitting for Resolver

### PR DESCRIPTION
**Pull request by tedliang**
Provide isSubmitting=true for Resolver when it's triggered by handleSubmit.

### CODE REVIEW

**Comment by bluebill1049** [comment]
can you try to inject into the `context` object?

**Comment by tedliang** [comment]
Thanks for your instant response! 
Yes, we can. Would be good the library can provide it. You can see the implement is very straight forward.

**Comment by tedliang** [comment]
According to the [handleSubmit documentation](https://react-hook-form.com/api#handleSubmit)
> Note: You can pass an async function for asynchronous validation. eg:
> handleSubmit(async (data) => await fetchAPI(data))

But the errors returned from fetchAPI are not being handled yet. 

When the form is submitted to the backend, errors will be returned if the data is invalid. 

We did a workaround with the resolver to handle the errors for this scenarios. That's why isSubmitting is required in resolver.

It will be ideal if the handleSubmit api can handle errors (similar to resolver).

**Comment by tedliang** [comment]
Please review the proper solution: https://github.com/react-hook-form/react-hook-form/pull/2515

**Pull request closed without merging**
