### PR TITLE
change from deepClone to shallowClone with defaultValues's reset

### PR DESCRIPTION
**Pull request by bluebill1049**
- [x] include information in the doc

### CODE REVIEW

**Comment by RPereiraRedspark** [comment]
i agree with this change, the deep clone broke the refs from my multiple selects, i use reset to bulk load all my form after a async get, i recently migrated from version 5 to 6 and noticed this new behavior, now i have to use setValue just for this field and trigger a redraw because of it

**Comment by bluebill1049** [comment]
> i agree with this change, the deep clone broke the refs from my multiple selects, i use reset to bulk load all my form after a async get, i recently migrated from version 5 to 6 and noticed this new behavior, now i have to use setValue just for this field and trigger a redraw because of it

It's very sad people doing the following.

```
const defaultValues = {xxxx}
reset(defaultValues)
```

hence the deepClone, I think this is a minor change will need to be included in the doc as well, so people aware of that, it's safer to use reset with not the same reference.

**Comment by RPereiraRedspark** [comment]
> > i agree with this change, the deep clone broke the refs from my multiple selects, i use reset to bulk load all my form after a async get, i recently migrated from version 5 to 6 and noticed this new behavior, now i have to use setValue just for this field and trigger a redraw because of it
> 
> It's very sad people doing the following.
> 
> ```
> const defaultValues = {xxxx}
> reset(defaultValues)
> ```
> 
> hence the deepClone, I think this is a minor change will need to be included in the doc as well, so people aware of that, it's safer to use reset with not the same reference.

The problem is, how do you reset fields such as Select without relying on the ref of the value? As setValue does not accept multiple values anymore, people will rely more the reset method to do such things

**Comment by bluebill1049** [comment]
> > > i agree with this change, the deep clone broke the refs from my multiple selects, i use reset to bulk load all my form after a async get, i recently migrated from version 5 to 6 and noticed this new behavior, now i have to use setValue just for this field and trigger a redraw because of it
> > 
> > 
> > It's very sad people doing the following.
> > ```
> > const defaultValues = {xxxx}
> > reset(defaultValues)
> > ```
> > 
> > 
> > hence the deepClone, I think this is a minor change will need to be included in the doc as well, so people aware of that, it's safer to use reset with not the same reference.
> 
> The problem is, how do you reset fields such as Select without relying on the ref of the value? As setValue does not accept multiple values anymore, people will rely more the reset method to do such things

can you share a codesandbobx?

**Comment by RPereiraRedspark** [comment]
> can you share a codesandbobx?

sure, https://codesandbox.io/s/sad-dust-vcgry?file=/src/App.js

in this case im simulating a fetch then using reset to populate o Controlled multi select, with setValue it works, with reset it  doesnt

**Comment by bluebill1049** [comment]
> > can you share a codesandbobx?
> 
> sure, https://codesandbox.io/s/react-hook-form-material-ui-select-multiple-vcgry
> 
> in this case im simulating a fetch then using reset to populate a Controlled multi select, with setValue it works, with reset it doesnt

You should compare with the `id` instead of the entire object.

**Comment by RPereiraRedspark** [comment]
the checkbox is only a visual help, the problem is the Select uses reference, updated the checkbox to not use reference check
https://codesandbox.io/s/react-hook-form-material-ui-select-multiple-forked-s6brs

**Comment by RPereiraRedspark** [comment]
as stated in the mui select docs, if i use anythig diferent to a string, it will use reference check
image

**Pull request merged**
