### PR TITLE
💨 close #8970 register field array cause render issue

### LINKED ISSUE #8970: issue: infinite renders with useFieldArray
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/naughty-curran-uwsfjm?file=/src/App.tsx

### Steps to reproduce

Open codesandbox and click 'add'

When using useFieldArray's rules field (even empty) + field with validation rules + subsription to form.formState.isValid browser hangs and in console you can see inf render logs
It seems that if I remove either of those 3 things all is working as expected

### Expected behaviour

Item should be added to form

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bluebill1049**
ref: https://codesandbox.io/s/cool-field-gw8rke?file=/src/src/useFieldArray.ts

close #8970

### CODE REVIEW

**Comment by Moshyfawn** [comment]
Yea, I couldn't figure out what was going on..

**Comment by bluebill1049** [comment]
> Yea, I couldn't figure out what was going on..

because `rules` is not been memorized, we are doing a developer favor by not asking them to `useMemo`, this applies to `defaultValues` as well. 


```tsx
const rules = useMemo(() => {props.value}, [props.value])

useFieldArray({
  rules,
})
```

this is the ideal way above.

**Review by Moshyfawn — APPROVED** [review]

**Comment by bluebill1049** [comment]
thanks @Moshyfawn for the review ❤️

**Comment by Moshyfawn** [comment]
Hm.. I think I'm still getting the behavior, actually

**Comment by Moshyfawn** [comment]
[This is the latest generated csb](https://codesandbox.io/s/react-hook-form-v7-ts-template-forked-hpgoym?file=%2Fsrc%2FApp.tsx), I believe

**Comment by bluebill1049** [comment]
oops let me relook at it.

**Comment by Moshyfawn** [comment]
[Here a workspace with the repo example in the test app `useFieldArray` example](https://codesandbox.io/p/github/react-hook-form/react-hook-form/fix-8970?file=%2Fapp%2Fsrc%2FuseFieldArray.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A1%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7ifn02w004kloi3emtadhrt%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fapp%252Fsrc%252FuseFieldArray.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%253Aapp%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl7l9mtjl00oe2e68e3woyq4a%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252FuseFieldArray%252FformState%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%253Aapp%2522%252C%2522key%2522%253A%2522cl7l9m6qo00k32e6842u3vp43%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) _(for ease of iteration)_, if you find it useful. On package update, you can just Restart from the "More menu" on the top right

**Comment by Moshyfawn** [comment]
The last time I tried debugging, it looks like `isValid` is set to `true` and `false` back and forth. I couldn't figure out the reason

**Comment by nhtbao101** [comment]
@bluebill1049 
Hello sir!!!
I have a case when use watch(). Can you help me checking this case.
Note: _`I don't use useArrayField`_
My case is I have a array data and it is will render to a form => submit data form => correct
But when I change array data (new data will push to array field, not define position) => submit data form => incorrect

This is my example.
Step1: Add price and stock for input field
Step2: Click Submit button
Step3: Click button `Update Array2` to update data in form
Step4: Click Submit button
Step5: ReCheck data form of `variants` => data form of variants is wrong

I using react hook form to + shopify to render data like this
Can you checking it in my example. Thank you so much.
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-6mw3z9?file=/src/index.js

**Comment by nhtbao101** [comment]
@bluebill1049 I just reading about this [PR](https://github.com/react-hook-form/react-hook-form/issues/660)
And i knew when I update array data by add or delete, watch won't watch it.
And Just watch when I use `useFieldArray`. But I don't know how to assign data for `fields` in `useFieldArray` from real data.
EX: 

```
const { realData } = props;
const { fields } = useFieldArray({})
```

**Pull request merged**
