### PR TITLE
Added React Native test

### PR DESCRIPTION
**Pull request by keiya01**
I added React Native test and fixed jest.config.js to standardize test config.
But this config probably drop coverage rate because `projects` property in jest config is performed in each environment. If there is some better config, tell me it.

### CODE REVIEW

**Comment by bluebill1049** [comment]
This is awesome @keiya01 something i didn't pay great attention ! don't worry about the coverage at all!

**Comment by keiya01** [comment]
OK :) Thank you @bluebill1049!

**Comment by keiya01** [comment]
@bluebill1049 
I completed to add react-native test. Could you review the PR ?

**Review by bluebill1049 — APPROVED** [review]
Nice React Native test coverage!

**Pull request merged**
