### PR TITLE
Remove fieldState.invalid

### LINKED ISSUE #8195: Why is Controller fieldState naming inconsistent?
In formState 👉  `isValid` - boolean - Set to true if the form doesn't have any errors.
In fieldState 👉 `invalid` - boolean - Invalid state for current input.

This threw me off a bit. Had to go to the docs to find the `invalid` return object.

Just curious if this is a purposeful difference, and if so what is the reason?

Best,
Jeremy

### PR DESCRIPTION
**Pull request by Moshyfawn**
Closes: #8195

### CODE REVIEW

**Comment by Moshyfawn** [comment]
@bluebill1049 If we go with this breaking change, plz, ping me to update [the RHF docs](https://react-hook-form.com/api/useform/getfieldstate)

**Comment by Moshyfawn** [comment]
@bluebill1049 rejecting at this time?

**Comment by bluebill1049** [comment]
@Moshyfawn left a feedback in the original issue 👍

**Comment by Moshyfawn** [comment]
@bluebill1049 I've resolved the `refactor/fieldstate-invalid` -> `react-18` conflicts locally, but running the API report extractor, it looks like it's not in sync with the `react-18` branch.

Do you want me to commit the `api-extractor.md` after I ran the `yarn api-extractor` command?

**Comment by bluebill1049** [comment]
yea, let's run it and we can see the diff. should be minor this change.

**Comment by bluebill1049** [comment]
maybe easier to create a new PR from v8 root branch?

**Comment by Moshyfawn** [comment]
```bash
Run yarn api-extractor:ci
yarn run v1.22.18
$ node scripts/apiExtractor.js
FAILURE REASON The API Extractor report does not match the exported API. Please run `yarn api-extractor:build` to generate an updated report and commit it.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Ran `yarn api-extractor` but it looks like [the API Extractor Build](https://github.com/react-hook-form/react-hook-form/runs/6046908097?check_suite_focus=true) step is failing for some reason.

**Comment by Moshyfawn** [comment]
> maybe easier to create a new PR from v8 root branch?

Oh, I was going to. Good idea!

**Pull request closed without merging**
