### PR TITLE
Update package.json to set sideEffects to false

### PR DESCRIPTION
**Pull request by alexogar**
Set sideEffects to false

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
thanks 👍

**Comment by alexogar** [comment]
Do you know when release of next version might happen?

**Comment by Moshyfawn** [comment]
I'd say, in a day or two

**Comment by Moshyfawn** [comment]
@alexogar, https://github.com/react-hook-form/react-hook-form/releases/tag/v7.28.1

**Pull request merged**
