### PR TITLE
Fix: Add missing blur method to field ref

### PR DESCRIPTION
**Pull request by finn-leonidkaida**
Adding a missing `blur` method to field ref in `useController` hook.

### CODE REVIEW

**Comment by Moshyfawn** [comment]
Thank you for the contribution. The `ref` content is created in accordance with the web standard. I doubt this PR is going to be merged

**Comment by leonidkaida** [comment]
@Moshyfawn thank you for the response! We are using react-hook-form in React Native and are relying on the presence of `.blur()` method which is also a “standard” for an input in RN. Do you know if there is a workaround for this problem?

**Comment by bluebill1049** [comment]
thanks for the PR, what usage that you try to cover in react native?

**Comment by leonidkaida** [comment]
@bluebill1049 we were checking if there are any fields in a form unfilled and if there were no such fields we blurred the last field which removed the focus and dismissed the keyboard at the same time. Closing this PR because we found a workaround.

**Pull request closed without merging**
