### PR TITLE
improve handleSubmit with for of

### PR DESCRIPTION
**Pull request by bluebill1049**
- improve handleSubmit with `for` loop instead of over complicated reduce.

### CODE REVIEW

**Comment by kotarella1110** [comment]
@bluebill1049 I will review tonight!

**Comment by bluebill1049** [comment]
ty @kotarella1110

**Review by kotarella1110 — APPROVED** [review]
Wow! The code has been simplified!
Your work is awesome 💚

**Comment by bluebill1049** [comment]
Ty for the review :)

**Pull request merged**
