### PR TITLE
fix #2541 ie build

### LINKED ISSUE #2541: IE11 bug in 6.3.1
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js/get-iterator-method' in '/node_modules/react-hook-form/dist'

### PR DESCRIPTION
**Pull request by bluebill1049**
fix #2541 IE 11 build regression

### CODE REVIEW

**Comment by bluebill1049** [comment]
> 62 kB (24%)

I am confused with this...

**Review by kotarella1110 — APPROVED** [review]
Reverting #2489 is the highest priority. Thanks @bluebill1049 .
After merging this PR, we need to find a solution for #2468 and #2488 PR.

**Comment by kotarella1110** [comment]
> > 62 kB (24%)
> 
> I am confused with this...

It's very strange... 😕

**Comment by yhor1e** [comment]
@bluebill1049 @kotarella1110 

I checked #2541 .I think `"@babel/runtime-corejs3": "^7.10.4",` in devDependencies is wrong. (I should have fixed it.)

https://github.com/react-hook-form/react-hook-form/blob/v6.3.1/package.json#L59 

This PR #2489 I created needs `@babel/runtime-corejs3`.
But this https://babeljs.io/docs/en/babel-plugin-transform-runtime#corejs says `@babel/runtime-corejs3` should be in `dependencies` not but `devDependencies`.

> npm install --save @babel/runtime-corejs3

Additionally, React Hook Form `6.3.1` from the npm repository works fine. Please check the below pages.
* Web page: https://yhor1e.github.io/sandbox-react-hook-form/fixed/
* `package-lock.json`: https://github.com/yhor1e/sandbox-react-hook-form/blob/master/fixed/package-lock.json#L5169-L5173

Maybe I think the react-hook-form from the npm repository is built from `dependencies` and `devDependencies`.
But the code sandbox ( https://codesandbox.io/s/ecstatic-tesla-3khdi?file=/src/App.js ) is built from `dependencies`.
(I couldn't find the underlying document.)

I will create an issue or a pull request if you need it.

**Comment by bluebill1049** [comment]
Thanks for the detailed reply. Maybe we should ask users to install `@babel/runtime-corejs3` as a dependency ? probably an easier solution.

**Comment by yhor1e** [comment]
@bluebill1049 

Thank you for your quick response.
I think you are right, but the change below is needed.

https://github.com/react-hook-form/react-hook-form/blob/de3dc4404549dd893f3799c222050d8c4bce02b4/rollup/createRollupConfig.js#L67

```diff
+ ...(options.plugins || []),
-  options.plugins,
```

The [part](https://github.com/react-hook-form/react-hook-form/blob/de3dc4404549dd893f3799c222050d8c4bce02b4/rollup/rollup.ie11.config.js#L26-L37) in `rollup.ie11.config.js` not work without the above changes.

**Comment by bluebill1049** [comment]
Honestly, I a bit confused with the above diff, that generates different build with IE build, because for IE 11 build, it should always have plugs and why it's impact IE 11 build but not the other build?

**Comment by kotarella1110** [comment]
> @bluebill1049
> 
> Thank you for your quick response.
> I think you are right, but the change below is needed.
> 
> https://github.com/react-hook-form/react-hook-form/blob/de3dc4404549dd893f3799c222050d8c4bce02b4/rollup/createRollupConfig.js#L67
> 
> ```diff
> + ...(options.plugins || []),
> -  options.plugins,
> ```
> 
> The [part](https://github.com/react-hook-form/react-hook-form/blob/de3dc4404549dd893f3799c222050d8c4bce02b4/rollup/rollup.ie11.config.js#L26-L37) in `rollup.ie11.config.js` not work without the above changes.

I think so, too.

```js
const option = {
  format: 'cjs',
  formatName: 'ie11',
  env: 'production',
  input: pkg.source,
  tsconfig,
};

console.log(
  createRollupConfig({
    ...option,
    plugins: [
      getBabelOutputPlugin({
        plugins: [
          [
            '@babel/plugin-transform-runtime',
            {
              corejs: 3,
            },
          ],
        ],
      }),
    ],
  })
);
```

`options.plugins`:

```ts
{
  input: 'src/index.ts',
  output: {
    file: 'dist/index.ie11.production.min.js',
    format: 'cjs',
    name: 'ReactHookForm',
    sourcemap: true,
    globals: { react: 'React' },
    exports: 'named'
  },
  plugins: [
    { name: 'peer-deps-external', options: [Function: options] },
    {
      name: 'rpt2',
      options: [Function: options],
      watchChange: [Function: watchChange],
      resolveId: [Function: resolveId],
      load: [Function: load],
      transform: [Function: transform],
      generateBundle: [Function: generateBundle],
      _ongenerate: [Function: _ongenerate],
      _onwrite: [Function: _onwrite]
    },
    {
      name: 'node-resolve',
      buildStart: [Function: buildStart],
      generateBundle: [Function: generateBundle],
      resolveId: [Function: resolveId],
      load: [Function: load],
      getPackageInfoForId: [Function: getPackageInfoForId]
    },
    false,
    {
      name: 'replace',
      renderChunk: [Function: renderChunk],
      transform: [Function: transform]
    },
    { name: 'sourcemaps', load: [AsyncFunction: load] },
    { name: 'terser', renderChunk: [AsyncFunction: renderChunk] },
    [ [Object] ] //  ❌: incorrect
  ]
}
```

`...(options.plugins || [])`:

```ts
{
  input: 'src/index.ts',
  output: {
    file: 'dist/index.ie11.production.min.js',
    format: 'cjs',
    name: 'ReactHookForm',
    sourcemap: true,
    globals: { react: 'React' },
    exports: 'named'
  },
  plugins: [
    { name: 'peer-deps-external', options: [Function: options] },
    {
      name: 'rpt2',
      options: [Function: options],
      watchChange: [Function: watchChange],
      resolveId: [Function: resolveId],
      load: [Function: load],
      transform: [Function: transform],
      generateBundle: [Function: generateBundle],
      _ongenerate: [Function: _ongenerate],
      _onwrite: [Function: _onwrite]
    },
    {
      name: 'node-resolve',
      buildStart: [Function: buildStart],
      generateBundle: [Function: generateBundle],
      resolveId: [Function: resolveId],
      load: [Function: load],
      getPackageInfoForId: [Function: getPackageInfoForId]
    },
    false,
    {
      name: 'replace',
      renderChunk: [Function: renderChunk],
      transform: [Function: transform]
    },
    { name: 'sourcemaps', load: [AsyncFunction: load] },
    { name: 'terser', renderChunk: [AsyncFunction: renderChunk] },
    {
      name: 'babel',
      renderStart: [Function: renderStart],
      renderChunk: [Function: renderChunk]
    } // ✅: correct
  ]
}
```

> > 62 kB (24%)
> 
> I am confused with this...

This has been reduced in size because the babel plugin isn't working correctly.

**Comment by bluebill1049** [comment]
Thanks @kotarella1110 i will we will need to info the user to include the dependency. will move this into the next patch and update the changelog with this as well.

**Comment by yhor1e** [comment]
My understanding is the same as https://github.com/react-hook-form/react-hook-form/pull/2542#issuecomment-671677227 .

**Comment by kotarella1110** [comment]
> Thanks @kotarella1110 i will we will need to info the user to include the dependency. will move this into the next patch and update the changelog with this as well.

@bluebill1049 Please wait!
I might be able to fix this by loading `@rollup/plugin-commonjs` in ie11 build.
I will create a PR.

**Comment by bluebill1049** [comment]
@kotarella1110 please update on top of my PR 👍 thanks

**Pull request merged**
