### PR TITLE
feature: focus with trigger

### PR DESCRIPTION
**Pull request by bluebill1049**
## usage

```ts
trigger('test', { shouldFocus: true })
```

## Feature Request

#2791

### CODE REVIEW

**Comment by gsaandy** [comment]
is this ready to release?

**Review by kaisermann — DISMISSED** [review]
API looks great and simple enough 👍 

(not that my review means anything, just want to show support for this feature as well (I read the code of course  👀))

**Comment by bluebill1049** [comment]
Thank your ur review. It definitely means a lot from the community. We are at the refinement for 7.6, plan to release this 7.7 in the following weeks.

**Comment by kaisermann** [comment]
@bluebill1049 Thanks for merging this! Forgive me for asking, but 

> This only works when the input's reference is registered, it will not work for custom register as well.

Does this mean that it won't work with inputs inside `<Controller>...</Controller>`?

**Pull request merged**
