### PR TITLE
Remove charged terminology

### PR DESCRIPTION
**Pull request by grumpyoldman-io**
Hi there,

in line with this PR: https://github.com/react-hook-form/documentation/pull/378, I'm opening this PR as a suggestion, to remove racially-charged and marginalizing terminology; according to the Code Of Conduct:

>In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

I think it would be great to take a step and take the following two (minor) changes:

1. Replace "master" branch with "main" branch as the default branch. (this PR)
2. Add "other" to gender options (perhaps staying away from gender in the docs is even better) (other PR: https://github.com/react-hook-form/react-hook-form/pull/2269)

### CODE REVIEW

**Comment by bluebill1049** [comment]
`main` is not a working url, love the rest of the changes. thanks :)

**Comment by grumpyoldman-io** [comment]
@bluebill1049 I've added a list of possible steps to take on the other PR in order to move over to Main as the default branch.

**Comment by grumpyoldman-io** [comment]
@bluebill1049 

I've created two PR's:
documentation: https://github.com/react-hook-form/documentation/pull/379
react-hook-form: https://github.com/react-hook-form/react-hook-form/pull/2269

Here is a how-to to change the default branch name:
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by bluebill1049** [comment]
hey @grumpyoldman-io just curious the reason why you decided to send PR to react-hook-form? what trigger you for such action (out of my curiosity).

**Comment by grumpyoldman-io** [comment]
@bluebill1049 are you referring to why I suggested the change, or why I did it in the form of PR?

**Why the change?**
Some of the terminology that we have come to rely on in tech is racially-charged, or alludes to slavery. Here are some examples:

- "master/slave" (databases)
- "master" to denote the main, original or source of something (such as the default and mainline Git branch)
- "blacklist/whitelist" for blocked and allowed values

I believe we should make an effort to contribute to creating a tech industry that is more welcoming to everyone.

Related article:
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**why in the form of a PR?**
Because I think I should also personally contribute and make it as easy for you as possible to do this, IF you to decide to do this. In no way am I trying to force this, I'm just trying to lower the bar.

**Comment by bluebill1049** [comment]
> @bluebill1049 are you referring to why I suggested the change, or why I did it in the form of PR? I'll answer bot just in case :)
> 
> **Why the change?**
> Some of the terminology that we have come to rely on in tech is racially-charged, or alludes to slavery. Here are some examples:
> 
> * "master/slave" (databases)
> * "master" to denote the main, original or source of something (such as the default and mainline Git branch)
> * "blacklist/whitelist" for blocked and allowed values
> 
> I believe we should make an effort to contribute to creating a tech industry that is more welcoming to everyone.
> 
> Related article:
> https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
> 
> **why in the form of a PR?**
> Because I think I should also personally contribute and make it as easy for you as possible to do this, IF you to decide to do this. In no way am I trying to force this, I'm just trying to lower the bar.

Respect above, take a look at the branches, I am preparing for the change.

**Comment by grumpyoldman-io** [comment]
@bluebill1049 if you need help, feel free to reach out. This package is become even more awesome!

**Comment by grumpyoldman-io** [comment]
@bluebill1049 FYI, I've changed the base of this PR to `main`

**Comment by bluebill1049** [comment]
kk 👍

**Comment by pmaier983** [comment]
Hey guys! Fully support the move from master -> main, but as I was just reading GitHub is planning on releasing support for this transformation [in the near future](https://github.com/github/renaming), and actually [recommends waiting](https://github.com/github/renaming/blob/main/README.md#now-supporting-early-movers-) until their work is done before changing.

I suggest we archive this PR and wait for added support form github!

Thanks for all the hard work grumpyoldman-io 😄

**Comment by bluebill1049** [comment]
> Hey guys! Fully support the move from master -> main, but as I was just reading GitHub is planning on releasing support for this transformation [in the near future](https://github.com/github/renaming), and actually [recommends waiting](https://github.com/github/renaming/blob/main/README.md#now-supporting-early-movers-) until their work is done before changing.
> 
> I suggest we archive this PR and wait for added support form github!
> 
> Thanks for all the hard work grumpyoldman-io 😄

Yay!

**Comment by bluebill1049** [comment]
Life is much easier when Github can sort this out :)

**Comment by pmaier983** [comment]
Closing this PR (archiving) until [github fully supports the change](https://github.com/github/renaming)

**Pull request closed without merging**
