### PR TITLE
ci: 🎡 add the node_modules folder to the cache

### PR DESCRIPTION
**Pull request by yonycalsin**
with each commit it runs the github-actions jobs and with this (yarn install).

What I am doing is that I am adding the folder (node_modules) to the cache, so it will not run (yarn install) with each commit only when (yarn.lock) has been modified.

### CODE REVIEW

**Comment by yonycalsin** [comment]
@bluebill1049  I thought I broke something, fortunately not. :+1:

the (ci/circleci: build ) error occurs in (npm run build) I can't tell you why, I checked it because I created a commit where I revert the applied changes, and still the error occurs.

https://app.circleci.com/pipelines/github/react-hook-form/react-hook-form/7254/workflows/96b0dc93-2cd4-4d9d-a174-e8ac9322e5cc/jobs/9702

**Comment by bluebill1049** [comment]
Thanks for your contribution again! @yonycalsin  you want to point into V7?

**Comment by yonycalsin** [comment]
Yes of course, it would be a pleasure to contribute to this wonderful library 👍

**Comment by bluebill1049** [comment]
looks like it caused a conflict, could you please resolve it when you have sometimes?

**Comment by yonycalsin** [comment]
@bluebill1049  done, conflicts resolved. :+1:

**Comment by bluebill1049** [comment]
Sweet! thank you.

**Pull request merged**
