### PR TITLE
improve SubmitHandler types

### PR DESCRIPTION
**Pull request by Yama-Tomo**
# origin

https://github.com/react-hook-form/react-hook-form/issues/1362#issuecomment-640515365

### CODE REVIEW

**Review by kotarella1110 — COMMENTED** [review]
@Yama-Tomo Thanks for your PR 💚 
But this PR does not support nested object.
We need to support nested object as well as flat object.

```ts
type DeepFormValues = {
    foo: string;
    bar: number[];
    baz: string[];
    deep: {
        foo: {
            bar: string[]
        }
    }
};

type Result = NullableArrayProperties<DeepFormValues>;
// type Result = {
//     foo: string;
//     bar?: number[];
//     baz?: string[];
//     deep: {
//         foo: {
//             bar: string[];
//         }
//     }
// }

const res: Result;
res.foo // (property) foo: string
res.bar // (property) bar?: number[] | undefined
res.baz // (property) baz?: string[] | undefined
res.deep.foo.bar // (property) bar: string[]
```
[CodeSandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-v5l61)
[TypeScript Playground](https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcDSA7CB3DbiIDyAZgDwAqAfHALxwDeAUHHANoAKcAlhnANYEIxOOQC6ALjgBnGFB4BzOKBjAMAEylxOAfjgZgAN2BQ4kjAFcAtgCNjSkCvWadew3cnsA3IwC+9xxoMbOTkABZcUgCqFlLAaty8AohCIhIJxHbkAGoAhgA25qg+zHC62fmFJWZuUN6MoJCwCMiomDh4BLkFwCQU1HTsXADGfBQANOhYuPhEZFSUdQ3Q8EgocAByEDDr5nl5AIJQUDmI5C0zvVS0DCUcCfyCwmIAtNqS5Byi-qqBh8eIpByGEQ1F0nGqRlqvm+TiCrBC4SiMTi9ySKTEkh4GRM5W6cGKLDKXUqLAhxkW4GWzTW5AgOz2OWseWAfxO7CgEBQsC4wCkfWu7By3PypBKgxG4w2W3pByOJzOKAuc0olEYC3qlKaq1Q4r4mxgrMQ7M5xhgPL5VzohEsXBgkv1MsNCuASr66o1jRWLQ2uzyjOZhuNXLNvP5dFpMv9LLlRo5wfNopYbWmnQqPWVargADIxcM9VtA3HTQnkx1EMT027syVrbbJaXXfNPHAAPQtuDEaBwpKSGRyDDyNJAxD4ib0Ng9vRWWxQIfAxiMbVwAAiwGAYAAYtBLBXNHQmCwWJ2IL3ZApvIe4NYhWZp8ZWKIL4frwAvU-9+QPp8sNRrsCSA9L0PY8AJKICgOvKB3wUB8wKAglD2KHw6iXAAlXldngOhIyZaN-iDYtQ1XdctygHc0ykdU22pVB0KkTDriYajLxA6QzwHbxmOfIU3inGx70fRguJYV9eL7GDBOEuBf3XUCpJYiATxueTwKvG82I-L8hPbVT8W0+D9OKRghggDAZDgKBeUkOjMO8SypAAOmPVt2wACjAItYEQABKDtFOggdGHshzIJcuB3M8pBfMg3iLH4qAHzgAAfOBzHUYBiB4OIgt5EKchfMKIpNLzovysT2M-L4UrS39Mv0NQcscmSwCcxS8pMaiiuDHy1KgjSJKAA)

**Comment by Yama-Tomo** [comment]
@kotarella1110  Thank you for your feedback
So, the expected value of the above example is this?

```typescript
// type Result = {
//     foo: string;
//     bar?: number[];
//     baz?: string[];
//     deep: {
//         foo: {
//             bar?: string[];
//         }
//     }
// }

res.deep.foo.bar // (property) bar?: string[] | undefined
```

**Comment by kotarella1110** [comment]
@Yama-Tomo The expected type are:

```ts
type DeepFormValues = {
    foo: string;
    bar: number[];
    baz: string[];
    deep: {
        foo: {
            bar: string[]
        }
    }
};

type Result = NullableArrayProperties<DeepFormValues>;
// type Result = {
//     foo: string;
//     bar?: number[];
//     baz?: string[];
//     deep?: {
//         foo?: {
//             bar?: string[];
//         }
//     }
// }
```

**Comment by Yama-Tomo** [comment]
@kotarella1110 I've edited

**Review by kotarella1110 — CHANGES_REQUESTED** [review]
@Yama-Tomo Thanks for your hard work :pray:
I don't think this PR can cover all cases.
If you have nested object and array as below, you cannot get the expected type.

```ts
type Form = {
  name: string;
  deep: {
    nested: {
      friends: FriendForm[];
    };
    test: string;
  };
};
type FriendForm = { name: string };
```

[CodeSandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-s9jtf)

As I commented here https://github.com/react-hook-form/react-hook-form/issues/1362#issuecomment-641093982, I think it's better to define `FormValues` generics parameter ​​on the user side.

@bluebill1049 What do you think?

**Comment by Yama-Tomo** [comment]
Hmmm... Sorry.. I don't understand the type you're expecting.
I implemented based on this comment, am I wrong?
https://github.com/react-hook-form/react-hook-form/pull/1824#issuecomment-641180901

```typescript
type Form = {
  name: string;
  deep: {
    nested: {
      friends: FriendForm[];
    };
    test: string;
  };
};
type FriendForm = { name: string };

type Result = NullableArrayProperties<Form>;
//type Result = {
//  name: string;
//  deep?: {
//    nested?: {
//      friends?: Array<{ name?: string }>;
//    };
//    test?: string;
//  };
//};
```

As mentioned here, the current type definition can cause runtime errors.
https://github.com/react-hook-form/react-hook-form/issues/1362#issuecomment-640515365

I don't think it's smart to make the `FormValue` type  to optional just to get around it.

**Comment by bluebill1049** [comment]
hey @Yama-Tomo, I do really appreciate your hard work toward this Type improvement, however, I do see how complicated it gets and I would say it's not going to be a general use case. I am lean towards what's @kotarella1110 suggested above. 

Let's keep this PR open as a reference and let the team decided whether if there is a thing we can leverage.

**Comment by kotarella1110** [comment]
> https://github.com/react-hook-form/react-hook-form/pull/1824#issuecomment-643633998

Can you submit and see the console output?

スクリーンショット 2020-06-14 11 17 05

This expected type is as follows:

```ts
type Result = NullableArrayProperties<Form>;
//type Result = {
//  name: string;
//  deep: {
//    nested?: {
//      friends?: Array<{ name?: string }>;
//    };
//    test: string;
//  };
//};
```

It is impossible for a library to support this.

**Comment by Yama-Tomo** [comment]
@kotarella1110 
> Can you submit and see the console output?

I checked. 🙏 

> This expected type is as follows:
>    ..... 
> It is impossible for a library to support this.

How about this?

[typescript playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=112&pc=1#code/KYDwDg9gTgLgBDAnmYcDSA7CB3DbiIDyAZgDwAqAfHALxwDeAUHHANoAKcAlhnANYEIxOOQC6ALjgBnGFB4BzOKBjAMAEylxOAfjgZgAN2BQ4kjAFcAtgCNjSkCvWadew3cnsA3IwC+9xxoMbOTkABZcUgCqFlLAaty8AohCIhIJxHbkAGoAhgA25qg+zHC62fmFJWZuUN6MoJCwCMiomDh4BLkFwCQU1HTsXADGfBQANOhYuPhEZFSUdQD0iwC0a+sbm1vb64z14NDwSChwACLAwGDsObBc+X20DCWsaAn8gsJi2pLkL6L+qkCAEEoFAcohSDwMiZIpQSixdCCwRDzpdrrd7rC4SwWD8-gCnHAAErAHJqCAYPKIJHgyEYaFwWHw0rE0nkynU0G01FXG4wO55UhY5l4tD-ZSAzQkobQNSkGRyDDyCbmDB8KYYbE43Q89H8+6-MVa3EiP7eHx1BqHZonACSUiBeTyhDA-Ip+S6hUI1gAVsAhjAHnQmCwOG8kikxCtvqb2OKHJK4DSITkMIhjSzZJUcaY4Kq1MBiDw4gTAr848zdFngCLY-GAlL-bL5bIFBNU+nK3B7Y7na6uO68p6er7-YG2tNOhUenMOKJKBnJMR8rFzaXGzKoHKFW2EFBClqq-uaybl3lV3srU1jqgXW6MPkZlIg09Q5weO9kp9RNHJDuleuWhdvoRhQLWFg2HYEqEuwwE1LW+aFsW8TQWWc5drBOZ4nGgHJqQHYZromE4th9aJtKzb-sqcAEV2PZOneA4PkO07en6AakBOHSIMOvTlvO1CoZo1bMgiQE5iaIHGOBNRrkJr7BGEETROYsTxB+EbfpIUKZMO5olGUw5VK4oGWgc14tGcFxgIxg4AMrmNYlhcDApw5DAOQviGbDvokHypKRgEUVuLaKtRtE5rotnMQ5TkuW5HkUHOi51uaZmNEclnRfksXOa57k5AAQogXHDs+VCPKq6rtIB2V5E+fQGSIxm6nyAqkIMIzjHAdUNfM1AAGSiVZlx1bl8UFaQhB5d1vUEOVC4LJe5mZScY2OXlCWeRVdDrXF+UecVpXTs+JRcTMvFzHCg0lNNLndedBB8QunhwMscDENAQSsEkf6tkqaQdnAPgTPQbC-XoVi2FAgNpsDezLDsSPIxsew3iIjx7Ztk3eZ9EB-WF3gsHjABMMZUUTcDWDcMZ4RB0NLSw1MAF6SHhVGM3AoQQPIwBs1yEJg-oMhxPzyKhQo1A+JzBaXJI3nExA+MKTmNzIgTCisKIlMsBaJR6ywstgCT8vMsLKhqKbEkfXIkpi7SQs5JYfPSP9ijSzrwOeyoMga0qlN6x7ewyhgMgIMAvumv8dBa94PswAAdGAqmhAAFGDeOSAA5FnExGybQTx9n8dZ8DwMAJR1PHScp+nH1K9nudwEb8sg831kF2DRdwFnJdlz4leMNXydSGnGcNz3Tct0EmcMH4bf5-L4eR73EcwKX8+D8Ptfj8rOd59ZS+z2DavgpIWv9wflyd8vMDF2vG8V1Xa816Pdez-v7fX0v3erzITfm1FnPfuW8X4jzHvXPeU8O4-zXvff+ExAGWxnrbJw59-jzyfkPMBO9IGNyvsbWBK8S6ILXkAjOqCNDn3oD4DBIC444LfrvfBX9CGFzgT3EhrgRbIIoVwO2bBHbO0bsDOhm86h7EkVIxgQA)

**Comment by kotarella1110** [comment]
> https://github.com/react-hook-form/react-hook-form/pull/1824#issuecomment-643853118

wow! 👀 this is amazing!
Can you support `NestedValue`?

🙅‍♂️ `NullableArrayProperties<UnpackNestedValue<TFieldValues>>`
🙆‍♂️ `UnpackNestedValue<NullableArrayProperties<TFieldValues>>`

The generics parameter passed to `NestedValue` should ignore the optional definition.

However, as Bill said, we should consider merging this PR because of the added complexity.

**Comment by Yama-Tomo** [comment]
Sure. If there's a chance it could be merged, we'll fix it.

**Pull request closed without merging**
