### PR TITLE
minor code improvement

### LINKED ISSUE #2884: Unnecessary Render when Using useFieldArray
**Describe the bug**
Typing on field that doesn't have rules when there is an error on other fields causes the component to rerender.

**To Reproduce**

1. Go to the sandbox
2. Click submit.
3. There should be error for address field.
4. Type on firstName or lastName field.
5. See the increased renderCount as you type.
6. Reload the page
7. Uncomment line 52
8. Click submit.
9. Typing on firstName will increase the renderCount but not for lastName

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-t0r1t

**Expected behavior**
Typing on field that doesn't have rules should not increase the renderCount

**Additional context**
Using react-hook-form v6.7.2

### PR DESCRIPTION
**Pull request by bluebill1049**
minor code improvement

close #2884

### CODE REVIEW

**Review by kotarella1110 — DISMISSED** [review]
👍

**Comment by bluebill1049** [comment]
> 👍

wow that was quick, thanks @kotarella1110

**Review by pmaier983 — APPROVED** [review]
LGTM!

**Comment by bluebill1049** [comment]
Thanks @pmaier983 for the review.

**Pull request merged**
