### PR TITLE
add File and FileList interface for ReactNative

### LINKED ISSUE #6479: [Bug] [ReactNative]: Property 'xxx' does not exist on type 'FieldError' (Cannot find name 'FileList' in node_modules/react-hook-form/dist/types/utils.d.ts)
### Version Number

7.15.0

### Codesandbox/Expo snack

Cannot reproduce on Web

### Steps to reproduce

1. `npx react-native init MyApp --template react-native-template-typescript`
2. `cd MyApp`
3. `yarn add react-hook-form`
4. Replace `App.tsx` with:
```tsx
// App.tsx
import React from 'react';
import {useForm} from 'react-hook-form';
import {View} from 'react-native';

interface FormData {
  firstName: string;
}

export default function App() {
  const {
    formState: {errors},
  } = useForm<FormData>();

  console.log(errors.firstName);

  return <View />;
}
```

5. **Error:** `Property 'firstName' does not exist on type 'FieldError'.ts(2339)`

### Expected behaviour

No errors, or at least a mention on how to fix this error on the documentation

### How to fix

When you open file `node_modules/react-hook-form/dist/types/utils.d.ts`, there are errors as well:
- Cannot find name 'FileList'
- Cannot find name 'File'

If you remove the mentions of FileList and File, or if you add

```
interface File extends Blob {
    readonly lastModified: number;
    readonly name: string;
}

interface FileList {
    [Symbol.iterator](): IterableIterator<File>;
}
```
The error goes away (thanks https://github.com/react-hook-form/react-hook-form/issues/2419#issuecomment-669718660)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kotarella1110**
## Overview

I solved #2518 by adding `global.d.ts` before. 
However, this does not seem to be working well.
The correct solution is to add the `global.d.ts` type to `DefinitelyTyped`.
ref: https://github.com/testing-library/jest-dom/issues/123
So I removed `global.d.ts`.

To ensure that this is solved, I defined it in a file that uses the DOM interface (`File` / `FileList`).

## Issues

close #6479

### CODE REVIEW

**Comment by kotarella1110** [comment]
@bluebill1049 Please publish a beta version to test this 🙏🏻

**Comment by bluebill1049** [comment]
`react-hook-form@7.15.2-beta.0` thanks @kotarella1110

**Comment by kotarella1110** [comment]
@bluebill1049 resolved!

スクリーンショット 2021-09-09 9 47 23

**Comment by bluebill1049** [comment]
awsome! thanks @kotarella1110

**Pull request merged**
