### PR TITLE
closure complier

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by bluebill1049** [comment]
@kotarella1110 do you know how to remove the license banner in rollup output?

**Comment by kotarella1110** [comment]
@bluebill1049 sorry. I don't know about it.

**Comment by paambaati** [comment]
@bluebill1049 Perhaps https://github.com/mjeanroy/rollup-plugin-strip-banner?

**Comment by bluebill1049** [comment]
> @bluebill1049 Perhaps https://github.com/mjeanroy/rollup-plugin-strip-banner?

Thanks, i tried that, i didn't work. If i can remove the banner, we can lose some good weight for this lib.

**Comment by bluebill1049** [comment]
nvm i didn't help the size...

**Pull request closed without merging**
