### PR TITLE
remove unnecessary map function within triggerValidation

### PR DESCRIPTION
**Pull request by kotarella1110**
fix https://github.com/react-hook-form/react-hook-form/pull/666#discussion_r358303301.
Sorry, [this comment](https://github.com/react-hook-form/react-hook-form/pull/666#discussion_r358301600) was already fixed.

### CODE REVIEW

**Comment by bluebill1049** [comment]
i think you miss one fix? there are two you spotted.

**Comment by bluebill1049** [comment]
Screen Shot 2019-12-17 at 11 27 49 am

**Comment by kotarella1110** [comment]
I'm sorry, I misunderstood!
One was already fixed!

**Comment by bluebill1049** [comment]
oh cool

**Comment by bluebill1049** [comment]
thanks!

**Pull request merged**
