### PR TITLE
do not passing refs to logic functions

### PR DESCRIPTION
**Pull request by mh-alahdadian**
logic functions are getting data and calculate depend on it so they don't have callback function which needs to access  latest value in ref in future and it just want to access current value of ref which we can pass it directly 
in another way logic functions should not import React and should not depend on it so we shouldn't use refs in them 

in this PR tests has been changed and remove current creating in them but I do not know what should I do with snapshot , please someone fix snapshots 

thank you

### CODE REVIEW

**Comment by MHA15** [comment]
@bluebill1049

**Comment by bluebill1049** [comment]
Thanks for the PR @MHA15 i will take a look this issue probably a bit later.

**Comment by MHA15** [comment]
> Thanks for the PR @MHA15 i will take a look this issue probably a bit later.

thank you and please fix snapshots of tests I did not work with them yet

**Comment by bluebill1049** [comment]
hey @MHA15 I think I will update progressively, function by function rather in one PR.

**Pull request closed without merging**
