### PR TITLE
fix #2538 formState with nested field array

### LINKED ISSUE #2538: Name with nested behaviour (using dot in name) causes dirtyFields to misbehave
Name with nested behaviour (using dot in name) causes dirtyFields to misbehave

The CSB shows that in 'the name without nested', when type random text to make the field dirty, then remove the item, the dirtyFields is behaving as intended.

However in CSB  in 'the name with nested', when type random text to make the field dirty, then remove the item, the dirtyFields is not behaving as intended. Will expect the dirtyFields not be like the results of CSB in 'the name with nested'.

(the behaviour can be checked in console.log)
name with nested: https://codesandbox.io/s/react-hook-form-usefieldarray-template-wlx4i?file=/src/index.js
name without nested: https://codesandbox.io/s/react-hook-form-usefieldarray-template-hjdq4?file=/src/index.js

### PR DESCRIPTION
**Pull request by bluebill1049**
close #2538 

https://codesandbox.io/s/react-hook-form-usefieldarray-template-t1qff

- stop accessing `formState` root level.
- stop updating `formState` root level.

### CODE REVIEW

**Comment by bluebill1049** [comment]
@keiya01 could you take a look this PR?

**Comment by keiya01** [comment]
@bluebill1049 I will review this PR. I'm sorry for delay🙏

**Comment by bluebill1049** [comment]
Thank you very much! sorry for pushing to get this issue over the line. ❤️

**Comment by keiya01** [comment]
Hmm, when I click `append` and `remove` button  after I enter some text to default field and remove default field, `dirtyFields` is not empty object.

**Comment by bluebill1049** [comment]
@keiya01 please test again, i think i forgot to save the latest in the CSB.

**Comment by keiya01** [comment]
@bluebill1049 I tested with updated CSB but my issue is not fixed ...

**Comment by bluebill1049** [comment]
oh i see the problem now! thanks @keiya01 i will looking into it.

**Comment by keiya01** [comment]
Sure. Thank you 🙏

**Comment by bluebill1049** [comment]
fixed, i will follow up with a unit test for this.

**Comment by bluebill1049** [comment]
updated @keiya01 thanks for the testing! 👍

**Comment by keiya01** [comment]
> Hmm, when I click `append` and `remove` button after I enter some text to default field and remove default field, `dirtyFields` is not empty object.

@bluebill1049 
This issue might be not fixed ...

**Comment by bluebill1049** [comment]
Screen Shot 2020-08-11 at 5 51 04 pm
Screen Shot 2020-08-11 at 5 51 07 pm

hmmm the unit test is passing and i tested manually. do i miss anything?

**Comment by keiya01** [comment]
Probably, you need to enter text and remove default field before `append`.

**Comment by bluebill1049** [comment]
Do you mean delete all inputs and there is still `dirtyFields` in the console?

**Comment by keiya01** [comment]
@bluebill1049 That's right.

**Comment by bluebill1049** [comment]
That's correct behavior 👍 because the field is deleted and which means they r dirty now.

**Comment by keiya01** [comment]
@bluebill1049 Oops... I see. Thank you.

**Review by keiya01 — APPROVED** [review]

**Comment by bluebill1049** [comment]
@keiya01 Thanks for the detailed review!

**Comment by kayuapi** [comment]
> That's correct behavior  because the field is deleted and which means they r dirty now.

I deleted the default field but the dirty fields is still empty

**Pull request merged**
