### PR TITLE
revert getValues defaultValues update

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Review by keiya01 — DISMISSED** [review]
LGTM. I'm sorry that my changes make cause some issue...

**Comment by bluebill1049** [comment]
@keiya01 don't be silly! we are really greatful for your contribution, we made this thing together and don't play the blame games here. Thank you!

**Comment by keiya01** [comment]
@bluebill1049 That's right... Thank you very much 🙏

**Comment by keiya01** [comment]
@bluebill1049 I commit some test that is removed to this PR now.

**Comment by bluebill1049** [comment]
> @bluebill1049 I commit some test that is removed to this PR now.

kk, no rush to merge this branch, feel free to commit on top it. I will wait for a round of feedback on that issue before merge and release the minor version.

**Comment by royalrose123** [comment]
I am wondering does this change effect that I couldn't getValues for the element I didn't render. It means when I have two tab, I need to get tab A values in tab B. I can't use getValues to get tab A values if tab A didn't render. 

`<MultipleAssetsTab currentTab={currentTab} setCurrentTab={setCurrentTab}>
        {currentTab === TAB.ASSET_LIST && (
          <div>
            <input name='input111' defaultValue='test' ref={register} />

            <input name='input222' ref={register} />

            {errors.exampleRequired && <span>This field is required</span>}
          </div>
        )}

        {currentTab === TAB.CAMPAIGN_INFO && (
          <div>
            <input name='input333' ref={register} />
          </div>
        )}

        <input type='submit' />
      </MultipleAssetsTab>`

I see the example of [Tabs Form](https://codesandbox.io/s/tabs-760h9?file=/src/TabGroup.tsx:773-778). It set the values into state or store. Then get values from store between different tab. Does it work like this now? I am stalled in this issue for a while. But when I install react-hook-form@6.1.0. Then everything is resolved...

**Comment by bluebill1049** [comment]
@royalrose123 are you setting `shouldReigster: false`?

**Comment by royalrose123** [comment]
@bluebill1049 Yes, I tried it. But I still need to switch to Tab B first then I can keep Tab B values after I switch to Tab A. But my issue is I don't really need to switch to Tab B and I still can get Tab B values in Tab A. 
-
In v.6.1.0, I can get all values in the parents component. Even I didn't switch to any children yet.

**Comment by royalrose123** [comment]
@bluebill1049  By the way, you mean "shouldUnregister", right?

**Pull request merged**
