### PR TITLE
allow empty object in prepend, append and insert.

### PR DESCRIPTION
**Pull request by tanmen**
allow undefined form object.

issue: #827

before
```js
const { control } = useForm();
const { append } = useFieldArray({ control, name: "test" });
append() // <- error
```

after
```js
const { control } = useForm();
const { append } = useFieldArray({ control, name: "test" });
append() // <- arrow undfined or null
```

### CODE REVIEW

**Comment by bluebill1049** [comment]
hey @tanmen thanks for the PR, maybe it's easier to make sure the user put down an argument for the append() we can improve the doc.  if you support empty, then you need to deal with null and undefined as well. what do you think?

**Comment by tanmen** [comment]
@bluebill1049
maybe it's easier to make sure the user put down an argument for the append() we can improve the doc.
-> thank you :)

if you support empty, then you need to deal with null and undefined as well. what do you think?
-> i think too :) i try add type null.

If my perception is wrong, feel free to say.

**Comment by tanmen** [comment]
this sample code.
https://codesandbox.io/s/hopeful-dawn-wpeqr

I have question.
Can I check type in codesandbox?

**Comment by bluebill1049** [comment]
Sorry I meant, we should always ask dev to put an argument and not support an empty argument.

follow the `push`, eg:

`[1,2,3].push()` This will push nothing into the array

So to work around with the `append` issue you are having: I think you can simply do `append({})` and translate to js 

`[1,2,3].push({})` This will push something into the array.

**Comment by tanmen** [comment]
If always wanted an argument, I felt that only empty object was good, so I chose only empty object.

**Comment by bluebill1049** [comment]
> If always wanted an argument, I felt that only empty object was good, so I chose only empty object.
> what do you think?

sounds great 👍

**Comment by tanmen** [comment]
@bluebill1049 thank you :)
Can i add test?

**Review by bluebill1049 — DISMISSED** [review]

**Comment by bluebill1049** [comment]
> @bluebill1049 thank you :)
> Can i add test?

why not! ❤️

**Review by bluebill1049 — APPROVED** [review]
TY very much 👍

**Comment by tanmen** [comment]
Thank you always so much :)

**Pull request merged**
