### PR TITLE
create global.d.ts that defined the DOM interfaces for ReactNative

### LINKED ISSUE #2419: react-native typescript errors
**Describe the bug**
Using the module in a react-native typescript project yields these errors:

[uno]
[uno]  $ tsc -p tsconfig.build.json
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(11,126): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(46,17): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(47,24): error TS2304: Cannot find name 'Node'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(47,40): error TS2304: Cannot find name 'MutationObserverInit'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(115,15): error TS2304: Cannot find name 'HTMLOptionsCollection'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(116,13): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(117,13): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(128,15): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/form.d.ts(149,71): error TS2304: Cannot find name 'VoidFunction'.
[uno]  ../../node_modules/react-hook-form/dist/types/utils.d.ts(14,103): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/utils.d.ts(14,295): error TS2304: Cannot find name 'FileList'.
[uno]  ../../node_modules/react-hook-form/dist/types/utils.d.ts(16,103): error TS2304: Cannot find name 'FileList'.

**To Reproduce**
1. Install the project in a react-native typescript project
2. Add some usage of the module (assumedly any usage);

**Expected behavior**
Valid typescript compile

### PR DESCRIPTION
**Pull request by kotarella1110**
Projects that React Hook Form installed don't include the DOM library need these interfaces to compile.
React Native applications is no DOM available. The JavaScript runtime is ES6/ES2015 only.

To solve this, I created `global.d.ts` that defined the DOM interfaces.
Only React Native will have empty DOM interfaces, but React will not be affected.

close #2419

### CODE REVIEW

**Comment by kotarella1110** [comment]
@bluebill1049 Please merge this PR before merging this PR https://github.com/react-hook-form/react-hook-form/pull/2520.

**Review by bluebill1049 — DISMISSED** [review]
LGTM.

**Comment by bluebill1049** [comment]
oops, a few conflicts @kotarella1110

**Comment by kotarella1110** [comment]
@bluebill1049 yes. I will resolve conflicts 👍

**Review by bluebill1049 — APPROVED** [review]
Thanks @kotarella1110

**Pull request merged**
