### PR TITLE
V8: feature: useFieldArray rules props

### PR DESCRIPTION
**Pull request by bluebill1049**
close: #6879 

```tsx
useFieldArray({
  name: 'test',
  rules: {
    required: true,
    minLength: 2,
    maxLength: 10,
    validate: (fieldArrayValues) => {
      if (fieldArrayValues) {
        return 'valdiate Error'
      }
    }
  }
})

errors?.test?.root?.message
```

ref: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-iyejbp?file=/src/src/logic/createFormControl.ts

- [x] functional tests
- [x] units & automation tests
- [x] type tests

cc @Moshyfawn

### CODE REVIEW

**Comment by Moshyfawn** [comment]
OMG, is it React 18 time already?!

**Comment by bluebill1049** [comment]
fixed only a rendering count correcton

**Comment by Moshyfawn** [comment]
Shouldn't we update the [`react-18` branch](https://github.com/react-hook-form/react-hook-form/tree/react-18) instead and merge into others?

**Comment by bluebill1049** [comment]
yea, I want to do a quick test here before merging into react 18. feel free to commit to that branch if you want to :) it's safe now.

**Comment by Moshyfawn** [comment]
Sry, got sidetracked with work. Will review as soon as I wake up

**Comment by bluebill1049** [comment]
I am going to merge this PR first, @Moshyfawn you can leave feedback here and I will address them. 🙏  No pressure on the review too, we have real work as first priority to make a living ❤️  have a good weekend buddy ✌🏻

**Comment by Moshyfawn** [comment]
> I am going to merge this PR first, @Moshyfawn you can leave feedback here and I will address them. 🙏 No pressure on the review too, we have real work as first priority to make a living ❤️ have a good weekend buddy ✌🏻

Thanks for understanding, @bluebill1049! ❤️ Had to compromise this week, as there're a bunch of releases I have to prepare for.

Have a nice weekend, man! 🎊

**Pull request merged**
