### PR TITLE
add TypeScript example

### PR DESCRIPTION
**Pull request by kotarella1110**
- [x] NestedValue
- [x] Native Multiple Input
- [x] OnSubmit
- [x] Resolver
- [x] UseFormMethods
- [x] Control

### CODE REVIEW

**Comment by bluebill1049** [comment]
I have created a new section just for our supported types.

**Comment by bluebill1049** [comment]
If you can create the other 3 types in here, I can migrate the content to the website's TS page section.

**Comment by kotarella1110** [comment]
@bluebill1049 I will create the other 3 types in here 👍

**Comment by kotarella1110** [comment]
@bluebill1049 I created all examples that exported types! 💯  please review.

**Review by bluebill1049 — APPROVED** [review]
Awesome thank you! i will update the website, after that we will be V6 ready.

**Pull request merged**
