### PR TITLE
improve FieldErrors type

### LINKED ISSUE #987: Typescript: The property 'message' doesn't exists in 'FieldError | FieldErrors<any>[]'
**Describe the bug**

The property 'message' doesn't exists in 'FieldError | FieldErrors<any>[]'.
The property 'message' doesn't exists in type 'FieldErrors<any>[]'.ts(2339)

This happens in typescript when trying to access errors messages from Autocomplete component from yup validation schema

**Codesandbox link**

Look at line 48!!!

https://codesandbox.io/s/material-demo-o15mc

**Screenshots**

image

### PR DESCRIPTION
**Pull request by kotarella1110**
fixed codesandbox
https://codesandbox.io/s/fancy-wildflower-sin9i

スクリーンショット 2020-03-10 15 17 54

related Issue
* https://github.com/react-hook-form/react-hook-form/issues/987

related PR
* https://github.com/react-hook-form/react-hook-form/pull/1083
* https://github.com/react-hook-form/react-hook-form/pull/1178

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
I will create another PR to locking those types in a test file. Really amazing stuff!

**Comment by kotarella1110** [comment]
@bluebill1049 That's great! What will the test tool use?
The following tools may be good:

* https://github.com/ikatyang/dts-jest
* https://github.com/SamVerschueren/tsd

**Comment by bluebill1049** [comment]
Oh cool awesome! I will take a look that.

**Comment by stramel** [comment]
I have used both of those before. Whichever is fine with me.

**Comment by stramel** [comment]
Nice work @kotarella1110! I was just thinking that the type needed improved.

**Pull request merged**
