### PR TITLE
improve RegisterOptions type

### PR DESCRIPTION
**Pull request by kotarella1110**
スクリーンショット 2021-02-11 14 59 00
スクリーンショット 2021-02-11 14 59 37

### CODE REVIEW

**Comment by kotarella1110** [comment]
@bluebill1049 Oh, did you set the argument of validate function to `any` because this has a `valueAs` option?

**Comment by bluebill1049** [comment]
> @bluebill1049 Oh, did you set the argument of validate function to `any` because this has a `valueAs` option?

awesome stuff! thanks @kotarella1110 nah, `valueAs` is not happen at `validate` function.

**Review by bluebill1049 — APPROVED** [review]
👍 awesome

**Comment by kotarella1110** [comment]
@bluebill1049  thanks 🙌🏻

**Comment by bluebill1049** [comment]
Have you tried V7? what's your thoughts @kotarella1110?

**Comment by kotarella1110** [comment]
@bluebill1049 I tried v7. v7 is great 🎉
However, there are some improvements.
It seems that of setValue's name and value args type is not strict.
I have some questions and consultations🙏
 I will DM you when you get home 👍

**Pull request merged**
