### PR TITLE
fix #1069 controller reset issue

### LINKED ISSUE #1069: Problems resetting Controller
**Describe the bug**
There are a couple of issues here:

1. When `defaultValues` is NOT passed to the `useForm` hook, the `reset` method fails to reset `Controller` controlled components.
2. When `defaultValues` IS passed to the `useForm` hook, the `reset` method fails to reset `Controller` controlled components when passed `{}`.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-rhfinput-9l5m0

**Expected behavior**
I would expect the `reset` method to reset the `Controller` controlled components without the need for `defaultValues` and when passing `{}` to `reset`.

**Screenshots**
https://t.co/pyJuyD3SpF?amp=1

**Desktop (please complete the following information):**
 - OS: Windows, Mac OSX
 - Browser: Chrome
 - Version: 79

**Additional context**
- When `defaultValues` is passed and nothing is passed to `reset` it does work.
- When `defaultValues` is NOT passed, conditionally rendered `Controller`s DO properly reset.
- When `defaultValues` is passed and `reset` is called with `defaultValues` it DOES properly reset.

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by bluebill1049** [comment]
fixing the unit tests now.

**Review by stramel — DISMISSED** [review]

**Comment by stramel** [comment]
Can probably drop the `bundlesize` integration since we have the new github action.

**Comment by bluebill1049** [comment]
@stramel true, but still like to see the gzipped size :)

**Comment by stramel** [comment]
@bluebill1049 there is a compressed size action as well https://github.com/preactjs/compressed-size-action

**Comment by bluebill1049** [comment]
oh nice you want to send a PR on this while i fix the unit test.

**Comment by stramel** [comment]
Ah, you're already running it... The main difference is the minification step. Will have a PR out shortly

**Pull request merged**
