### PR TITLE
📄 `Form` Component

### LINKED ISSUE #9600: issue: can't get typescript to accept different schema output using zod
### Version Number

7.38.0

### Codesandbox/Expo snack

https://codesandbox.io/s/hidden-cloud-vruf30?file=/src/App.tsx:0-718

### Steps to reproduce

1. Open the Code Sandbox (https://codesandbox.io/s/hidden-cloud-vruf30?file=/src/App.tsx:0-718);
2. Look at the error at line 25;

### Expected behaviour

React Hook Form should automatically infer the output type for the schema sent via the `resolver` property or allow us to set the input and output schema types when using `useForm` hook.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bluebill1049**
# `Form` Component

- [x] tests
- [x] beta release
- [x] beta doc
- [x] RFC: https://github.com/react-hook-form/react-hook-form/discussions/9856
- [x] rc release

### 🥅 Context and goal

Improve DX and UX for forms.

- support progressive enhancement
  - Build-in validation will pass native constraint attribute to the inputs
  - Schema validation will not be covered in this PR since it requires external library support to serialise the schema attributes before hook form can start setting up all the input attributes
  
- support transformed value type overwrite
  - close #9600
- support build-in post submission  
  - This would greatly reduce the amount of code users would have to write for a post submission

**🧑🏻‍🍼BEFORE**

```tsx
const { handleSubmit } = useForm();

const onSubmit = async (data) => {
  await fetch('/api', {
    headers: {
      "content-type": 'application/json',
    },
    body: JSON.stringify(data)
  })
}

<form onSubmit={handleSubmit(onSubmit)} />
```

**👼🏻 AFTER**

```tsx
const { control } = useForm();

<Form 
  action="/api" 
  method="post" 
  control={control}
  headers={{
    "content-type": 'application/json',
  }}
/>
```

----

### 👨🏻‍💻 Code Example

Form Component prop `Type`

```tsx
type Props<
  T extends FieldValues,
  U extends FieldValues | undefined = undefined,
> = Partial<{
  control: Control<T>;
  children?: React.ReactNode | React.ReactNode[];
  render?: (props: {
    submit: (e?: React.FormEvent) => void;
  }) => React.ReactNode | React.ReactNode[];
  onSubmit: U extends FieldValues ? SubmitHandler<U> : SubmitHandler<T>;
  resolve: (response: Response) => void;
  reject: (response?: Response) => void;
  headers: Record<string, string>;
  validateStatus: (status: number) => boolean;
}> &
  React.FormHTMLAttributes<HTMLFormElement>;
```

- #### Progressive enhancement

```tsx
// so it will not introduce a breaking change, we can consider default in the next major
useForm({
  progressive: true
})

return (
  <Form control={control}>
    <input {...register('name', { required: true })} />
  </Form>
)

// Form render output:
<form>
  <input name="name" required />
</form>
```

- #### Type support for transformed values

```tsx
const defaultValues = { test: 'test' };

type FormValues = typeof defaultValues;
type TransformedFormValue = {
  test: number;
};

const Test = () => {
  const { control } = useForm({
    defaultValues: { test: 'test' },
  });

  return (
    <Form<FormValues, TransformedFormValue>
      onSubmit={(data) => {
        console.log(data); // data.test -> number
      }}
      control={control} // optional if not using context
    >
      <input />
    </Form>
  );
};
```

- #### Post Submission

Post a request after the successful validation data

```tsx
<Form 
  action="/api/submit"
  // headers={{ accessToken: 'xxx' }} // optional headers
>
  <input {...register('name')} />
</Form />
```

Manual onSubmit callback

```tsx
<Form onSubmit={data => fetch('/api')} />
  <input {...register('name')} />
</Form />
```

React Native

```tsx
<Form 
  action="/api/submit"
  // headers={{ accessToken: 'xxx' }} // optional headers
  render={({ submit }) => {
    return ( 
      <Button onPress={() => submit()}>
    )
  }}
/>
```

----

### ⛔️ Limitation 

- progressive enhancement
  - web
  - native build-in validation

### CODE REVIEW

**Comment by bluebill1049** [comment]
After start building the Form component and realise there are some further improvements nd opportunities for a better developer experience as well.

```
<Form>
```

**Comment by vladnicula** [comment]
@bluebill1049 coming from twitter here to ask for the RFC, cheers!

**Comment by bluebill1049** [comment]
hey, @vladnicula here is the RFC: https://github.com/react-hook-form/react-hook-form/discussions/9856 thanks!

**Review by annaescalada — DISMISSED** [review]

**Review by yeraysarmiento — DISMISSED** [review]

**Comment by pkasarda** [comment]
can we release this? 🙏 beta version is conflicting with resolvers :(

**Pull request merged**
