### PR TITLE
migration from ts-jest to @swc/jest

### PR DESCRIPTION
**Pull request by kotarella1110**
migration from @ts-jest to @swc/jest will speed up test run time by several times 💪

Run time in my local environment:

ts-jest

```
Time:        92.283 s
```

@swc/jest

```
Time:        37.284 s
```

### CODE REVIEW

**Comment by nvh95** [comment]
This is a great PR. I can confirm that `yarn test` runs well in my local environment too.
Local: Macbook Air 2020 M1

Before: 12.94s
Benchmark before

After: 6.86s
Benchmark after

**Comment by bluebill1049** [comment]
oh wow, half the duration!

**Review by bluebill1049 — APPROVED** [review]
Thanks for this awesome test speed uplift and @nvh95's verification.

**Comment by bluebill1049** [comment]
(before)
image

(after)
Screen Shot 2022-06-26 at 9 16 40 am

save Github action (world) energy 😆

**Comment by g3tr1ght** [comment]
Have you tried comparing against babel-jest or ts-jest with isolatedModules flag turned on? I would assume the results would be similar to swc.

**Comment by Upinwv** [comment]
H

--

**Pull request merged**
