### PR TITLE
Use bundlewatch instead of bundlesize

### PR DESCRIPTION
**Pull request by Moshyfawn**
[bundlesize](https://github.com/siddharthkp/bundlesize) has 10 vulnerability reports:
-  1 critical
- 7 high
- 2 moderate

Also, it seems like the package is very poorly maintained _(I mean the updates frequency / security fixes)_. There's a [bundlesize2](https://github.com/siddharthkp/bundlesize2) package, which is supposedly a 2.0 version of [bundlesize](https://github.com/siddharthkp/bundlesize) once finished, but it doesn't look promising.

I propose to switch to [bundlewatch](https://github.com/bundlewatch/bundlewatch/) instead.
- It has 0 security vulnerability reports 
- It's updated regularly
- The API is very similar to [bundlesize](https://github.com/siddharthkp/bundlesize)
- Supports CircleCI and GH status reports

If agreed, there's [a section related to GH CI status ](https://github.com/bundlewatch/bundlewatch/#ci-auth-variables-needed-by-bundlewatch=) in [bundlewatch](https://github.com/bundlewatch/bundlewatch/) docs. @bluebill1049 can you look through it and see you have the required environment config. It says, using CircleCI, it should be already fine.
> If you're using, Travis, CircleCI, Wrecker, Drone or GitHub Actions these should all work out of the box.

### CODE REVIEW

**Comment by Moshyfawn** [comment]
@bluebill1049 with all the latest PRs related to security vulnerabilities, we can close the [dependabot](https://github.com/apps/dependabot)'s bump PR.
- #8251
- #8113
- #8089
- #7863
- #7748

**Comment by bluebill1049** [comment]
thanks, @Moshyfawn yea I was thinking the same, in fact probably worth removing this later as well, because we already have Package Size / build (pull_request)  but let's get this PR merge :) we can sort that out later.

**Review by bluebill1049 — APPROVED** [review]

**Comment by Moshyfawn** [comment]
Ah, I was wondering why there 2 package size workflows!
Sounds good!

**Comment by bluebill1049** [comment]
Amazing stuff @Moshyfawn ~ We are maintaining the most maintained form library in the industry. ❤️

**Comment by Moshyfawn** [comment]
Ahaha, yea, we do be maintaining like that! LMAO 🍻

**Pull request merged**
