### PR TITLE
WIP on issue #579

### PR DESCRIPTION
**Pull request by bluebill1049**

### CODE REVIEW

**Comment by alias-mac** [comment]
@bluebill1049, this merge broke the types on errors that have nested fields, like `errors['address.street']`.

I wasn't able to trace the exact line, but the problem is that this makes `errors` defined as `Partial<Record<"firstName" | "lastName" | ...` and `address` in my case is a nested field, like `address.street`.

**Comment by bluebill1049** [comment]
hey, @alias-mac sorry to break your app... looks like I have miss that use case. I will try to patch that soon.

**Comment by bluebill1049** [comment]
hey @alias-mac  what about giving it a type for now until we release the next major version for the nested errors object. since optional chaining is getting better coverage, we can start doing `errors?.address?.street`

for now: is this going to fix your problem?
`['address.street']: string`?

**Comment by alias-mac** [comment]
@bluebill1049 thanks for the fast reply!
I upgraded to react-scripts 3.3.0 recently to get optional chaining 😄, so I agree with you on doing that. I believe that was your goal anyway by reading https://react-hook-form.com/api#errors

I added hack for now to keep using the latest version that contains this fix. It also helped me catch some inputs that weren't registered but were using the `errors` property (which would never be defined).

Thanks for keeping this library awesome 🎉 !
Looking forward on seeing the nested support working.

**Comment by bluebill1049** [comment]
thanks @alias-mac it should be pretty simple to switch to `errors` object, I did flat errors purely because optional chaining was not that popular at the time when I was designing the API. Cheers for the support! if you find it useful please consider to support us by leaving a  start too :) (no pressure tho)

**Pull request merged**
