### PR TITLE
⏭️ next (7.42.0)

### PR DESCRIPTION
**Pull request by bluebill1049**
📽 feature: validate function to include formValues (#9079)

```tsx
type FormValues = {
  number1: number;
  number2: number;
};

// Making exported validate function isolated for validation
export function validateNumber(_: number, formValus: FormValues) {
  return formValus.number1 + formValus.number2 === 3;
}

export default function App() {
  const { register, handleSubmit } = useForm({
    defaultValues: {
      number1: 0,
      number2: 0
    }
  });

  return (
    <form onSubmit={handleSubmit((data) => console.log(data))}>
      <input
        type="number"
        {...register("number1", {
          validate: validateNumber,
          valueAsNumber: true
        })}
      />
      <input
        type="number"
        {...register("number2", {
          validate: validateNumber,
          valueAsNumber: true
        })}
      />
     <button>submit</button>
    </form>
  );
}
```

🛤️ keep track of traversed types to avoid self-referencing while constructing paths for a type (#9540)
🏋🏻‍♀️ reduced code with unset by weight reduce of 1% (#9575)
📔 fix warning for setValue test case
🪜 Improve `handleSubmit` function

### CODE REVIEW

**Comment by cdbattags** [comment]
Any ETA for this? We're ready to make the switch from Formik once https://github.com/react-hook-form/react-hook-form/pull/9540 lands!

**Comment by bluebill1049** [comment]
@cdbattags you can use the `beta` for now:[7.42.0-next.0](https://github.com/react-hook-form/react-hook-form/pull/9603/commits/4078cd875d04dee00231cdba6803872414a4d0f8)  before we iron out any of the issues

**Comment by cdbattags** [comment]
Thanks, @bluebill1049. I'll try it out tomorrow morning.

**Comment by cdbattags** [comment]
Spent the whole day with this and no issues so far in my dev environment. I didn't use the `validate` function or the `handleSubmit` though.

Thanks again, @SimplyLinn!

**Pull request merged**
