### PR TITLE
remove touch mode and made touched by blur

### PR DESCRIPTION
**Pull request by bluebill1049**
after reading a few more docs and questions/answers. I realized touched should be only triggered by onBlur which means when control has lost focus. 

so I removed `touchedMode` and made default behavior to `onBlur` for touched state

### CODE REVIEW

**Comment by bluebill1049** [comment]
i will fix the automation tonight.

**Review by JeromeDeLeon — DISMISSED** [review]

**Comment by JeromeDeLeon** [comment]
The build seems to be failing for cypress

**Comment by bluebill1049** [comment]
yea thanks @JeromeDeLeon I will fix it all tonight, just want to get your thoughts on it. looks like you agree on such change. 👍 I will sort out the rest.

**Review by JeromeDeLeon — DISMISSED** [review]

**Comment by bluebill1049** [comment]
thanks @JeromeDeLeon for reviewing 👍

**Comment by rkurbatov** [comment]
@bluebill1049 it works perfectly for us, just as it was in redux-forms so now we can switch smoothly. But it's a breaking change, won't it affect somebody's else projects?

**Comment by bluebill1049** [comment]
@rkurbatov I think it was a mistake on the very get-go, now the behavior is correct. touched was meant to only trigger onBlur, not onChange. I will make this as a minor change and info people in the release note.

**Comment by leventeszmolka** [comment]
Hi,

It seems that on controlled inputs `touched` still gets triggered `onChange` and not `onBlur`.

**Comment by bluebill1049** [comment]
@leventeszmolka provide a codeandbox for us to reproduce

**Comment by leventeszmolka** [comment]
@bluebill1049 please see the codesandbox example here: https://codesandbox.io/s/wispy-smoke-50v9s?file=/src/App.js

**Comment by bluebill1049** [comment]
@leventeszmolka you are right on that, can you raise an issue on this?

**Comment by leventeszmolka** [comment]
@bluebill1049 I have raised the issue #1588. Many thanks for looking into it.

**Comment by jtomaszewski** [comment]
Would you consider adding `touchedMode = "onFocus" | "onBlur"` ? Depending on how you looked at it, I might consider a field as touched if the user has interacted with, that is they focused with it at least once. Why would we delay that until the blur event happens?

Our use case: I want to show a warning on a field "no 2", wheneveruser focuses on the field "no 3 or later", while not filling the field no 2 first.

**Pull request merged**
