### PR TITLE
feat: add react-server bundle

### PR DESCRIPTION
**Pull request by kotarella1110**
## Related Issues

- https://github.com/react-hook-form/react-hook-form/pull/11061
- close https://github.com/react-hook-form/resolvers/pull/636

## Changes Made

Server Actions are executed within the react-server context, which can lead to errors when importing react-hook-form within Server Actions.

> TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component

This results in errors even when using only react-hook-form logic in Server Actions.
This PR aims to enable the use of react-hook-form's logic and utilities within the react-server context. This is achieved by adding react-server through conditional exports.

Once this is merged, it will also make my previously created PR https://github.com/react-hook-form/resolvers/pull/636 for @hookform/resolvers unnecessary.

### CODE REVIEW

**Comment by kotarella1110** [comment]
@bluebill1049 
I checked out https://github.com/react-hook-form/react-hook-form/pull/11163 branch to check its functionality in CodeSandbox CI. Therefore, I kindly request that you merge https://github.com/react-hook-form/react-hook-form/pull/11163 first before merging this PR.

**Review by bluebill1049 — DISMISSED** [review]

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
Do you want to merge this?

**Comment by kotarella1110** [comment]
I want to merge this!

**Comment by joakim-roos** [comment]
Has this been released yet?

**Comment by chrisb2244** [comment]
> Has this been released yet? If so, which version?

@joakim-roos I *think* you want to be watching this PR: https://github.com/react-hook-form/react-hook-form/pull/11061
Looks pretty exciting...

**Comment by CombeeMike** [comment]
I'm experiencing issues caused by the `react-server` condition export which was added here.
See [this discussion](https://github.com/orgs/react-hook-form/discussions/11524) for more details.
I'd really appreciate some help with this.

**Pull request merged**
